---
sidebar: sidebar 
permalink: trident-docker/collect-logs-docker.html 
keywords: deploy, Trident, trident for docker, docker, logs, binary, managed plugin 
summary: 문제 해결에 도움이 되는 로그를 수집할 수 있습니다.  로그를 수집하는 데 사용하는 방법은 Docker 플러그인을 실행하는 방법에 따라 달라집니다. 
---
= 로그 수집
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
문제 해결에 도움이 되는 로그를 수집할 수 있습니다.  로그를 수집하는 데 사용하는 방법은 Docker 플러그인을 실행하는 방법에 따라 달라집니다.



== 문제 해결을 위한 로그 수집

.단계
. 권장되는 관리 플러그인 방식(예: 사용)을 사용하여 Trident 실행하는 경우 `docker plugin` 명령)을 다음과 같이 확인하세요.
+
[source, console]
----
docker plugin ls
----
+
[listing]
----
ID                  NAME                DESCRIPTION                          ENABLED
4fb97d2b956b        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
journalctl -u docker | grep 4fb97d2b956b
----
+
표준 로깅 수준을 사용하면 대부분의 문제를 진단할 수 있습니다.  그래도 충분하지 않다면 디버그 로깅을 활성화할 수 있습니다.

. 디버그 로깅을 활성화하려면 디버그 로깅이 활성화된 플러그인을 설치하세요.
+
[source, console]
----
docker plugin install netapp/trident-plugin:<version> --alias <alias> debug=true
----
+
또는 플러그인이 이미 설치된 경우 디버그 로깅을 활성화합니다.

+
[source, console]
----
docker plugin disable <plugin>
----
+
[source, console]
----
docker plugin set <plugin> debug=true
----
+
[source, console]
----
docker plugin enable <plugin>
----
. 호스트에서 바이너리 자체를 실행하는 경우 로그는 호스트에서 사용할 수 있습니다. `/var/log/netappdvp` 예배 규칙서.  디버그 로깅을 활성화하려면 다음을 지정하세요. `-debug` 플러그인을 실행할 때.




== 일반적인 문제 해결 팁

* 새로운 사용자가 겪는 가장 흔한 문제는 플러그인 초기화를 방해하는 잘못된 구성입니다.  이런 일이 발생하면 플러그인을 설치하거나 활성화하려고 할 때 다음과 같은 메시지가 표시될 가능성이 높습니다.
+
`Error response from daemon: dial unix /run/docker/plugins/<id>/netapp.sock: connect: no such file or directory`

+
이는 플러그인이 시작되지 않았음을 의미합니다.  다행히도 이 플러그인은 포괄적인 로깅 기능을 내장하고 있어, 발생할 수 있는 대부분의 문제를 진단하는 데 도움이 됩니다.

* 컨테이너에 PV를 장착하는 데 문제가 있는 경우 다음을 확인하십시오. `rpcbind` 설치되어 실행 중입니다.  호스트 OS에 필요한 패키지 관리자를 사용하여 확인하십시오. `rpcbind` 실행 중입니다.  rpcbind 서비스의 상태를 확인하려면 다음을 실행하세요. `systemctl status rpcbind` 또는 이에 상응하는 것.

