---
sidebar: sidebar 
permalink: trident-docker/known-issues-docker.html 
keywords: known issues, trident, trident for docker, docker 
summary: Docker와 함께 Trident 사용할 때 알려진 문제에 대한 정보를 찾아보세요. 
---
= 알려진 문제 및 제한 사항
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Docker와 함께 Trident 사용할 때 알려진 문제와 제한 사항에 대한 정보를 찾아보세요.



== Trident Docker Volume Plugin을 이전 버전에서 20.10 이상으로 업그레이드하면 해당 파일이나 디렉토리가 없다는 오류와 함께 업그레이드가 실패합니다.

.해결 방법
. 플러그인을 비활성화합니다.
+
[source, console]
----
docker plugin disable -f netapp:latest
----
. 플러그인을 제거하세요.
+
[source, console]
----
docker plugin rm -f netapp:latest
----
. 추가 기능을 제공하여 플러그인을 다시 설치합니다. `config` 매개변수.
+
[source, console]
----
docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json
----




== 볼륨 이름은 최소 2자 이상이어야 합니다.


NOTE: 이는 Docker 클라이언트의 제한 사항입니다.  클라이언트는 단일 문자 이름을 Windows 경로로 해석합니다. https://github.com/moby/moby/issues/25773["버그 25773을 참조하세요"^] .



== Docker Swarm에는 Trident 모든 스토리지 및 드라이버 조합을 지원하지 못하게 하는 특정 동작이 있습니다.

* Docker Swarm은 현재 볼륨 ID 대신 볼륨 이름을 고유한 볼륨 식별자로 사용합니다.
* 볼륨 요청은 Swarm 클러스터의 각 노드에 동시에 전송됩니다.
* 볼륨 플러그인( Trident 포함)은 Swarm 클러스터의 각 노드에서 독립적으로 실행되어야 합니다.  ONTAP 의 작동 방식과 `ontap-nas` 그리고 `ontap-san` 운전자가 기능하는 한, 이러한 제한 내에서 작동할 수 있는 유일한 운전자가 운전자입니다.


나머지 드라이버는 명확한 "승자" 없이 단일 요청에 대해 많은 수의 볼륨이 생성되는 결과를 초래할 수 있는 경쟁 조건과 같은 문제의 영향을 받습니다. 예를 들어 Element에는 볼륨의 이름은 같지만 ID는 다를 수 있는 기능이 있습니다.

NetApp Docker 팀에 피드백을 제공했지만 향후 대책에 대한 내용은 없습니다.



== FlexGroup 이 프로비저닝되는 경우, 두 번째 FlexGroup 에 프로비저닝되는 FlexGroup 과 공통된 집계가 하나 이상 있는 경우 ONTAP 두 번째 FlexGroup 프로비저닝하지 않습니다.
