---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, Trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config, nvme/tcp, nvme 
summary: Trident 배포하려면 먼저 호스트에 필요한 프로토콜 전제 조건을 설치하고 구성해야 합니다. 
---
= 배포를 위한 전제 조건
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident 배포하려면 먼저 호스트에 필요한 프로토콜 전제 조건을 설치하고 구성해야 합니다.



== 요구사항을 확인하세요

* 귀하의 배포가 모든 요구 사항을 충족하는지 확인하십시오.link:../trident-get-started/requirements.html["요구 사항"] .
* 지원되는 버전의 Docker가 설치되어 있는지 확인하세요.  Docker 버전이 오래된 경우, https://docs.docker.com/engine/install/["설치하거나 업데이트하세요"^] .
+
[source, console]
----
docker --version
----
* 호스트에 프로토콜 필수 구성 요소가 설치되고 구성되어 있는지 확인하세요.




=== NFS 도구

운영 체제에 맞는 명령을 사용하여 NFS 도구를 설치합니다.

[role="tabbed-block"]
====
.RHEL 8 이상
--
[source, console]
----
sudo yum install -y nfs-utils
----
--
.우분투
--
[source, console]
----
sudo apt-get install -y nfs-common
----
--
====

WARNING: 컨테이너에 볼륨을 연결할 때 오류가 발생하는 것을 방지하려면 NFS 도구를 설치한 후 작업자 노드를 재부팅하세요.



=== iSCSI 도구

운영 체제에 맞는 명령을 사용하여 iSCSI 도구를 설치합니다.

[role="tabbed-block"]
====
.RHEL 8 이상
--
. 다음 시스템 패키지를 설치하세요:
+
[source, console]
----
sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath
----
. iscsi-initiator-utils 버전이 6.2.0.874-2.el7 이상인지 확인하세요.
+
[source, console]
----
rpm -q iscsi-initiator-utils
----
. 스캐닝을 수동으로 설정:
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. 다중 경로 활성화:
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: 보장하다 `etc/multipath.conf` 포함하다 `find_multipaths no` 아래에 `defaults` .

. 확인하십시오 `iscsid` 그리고 `multipathd` 실행 중입니다:
+
[source, console]
----
sudo systemctl enable --now iscsid multipathd
----
. 활성화하고 시작하세요 `iscsi` :
+
[source, console]
----
sudo systemctl enable --now iscsi
----


--
.우분투
--
. 다음 시스템 패키지를 설치하세요:
+
[source, console]
----
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools
----
. open-iscsi 버전이 2.0.874-5ubuntu2.10 이상(bionic의 경우) 또는 2.0.874-7.1ubuntu6.1 이상(focal의 경우)인지 확인하세요.
+
[source, console]
----
dpkg -l open-iscsi
----
. 스캐닝을 수동으로 설정:
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. 다중 경로 활성화:
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: 보장하다 `etc/multipath.conf` 포함하다 `find_multipaths no` 아래에 `defaults` .

. 확인하십시오 `open-iscsi` 그리고 `multipath-tools` 활성화되어 실행 중입니다.
+
[source, console]
----
sudo systemctl status multipath-tools
sudo systemctl enable --now open-iscsi.service
sudo systemctl status open-iscsi
----


--
====


== NVMe 도구

운영 체제에 맞는 명령을 사용하여 NVMe 도구를 설치하세요.

[NOTE]
====
* NVMe에는 RHEL 9 이상이 필요합니다.
* Kubernetes 노드의 커널 버전이 너무 오래되었거나 커널 버전에서 NVMe 패키지를 사용할 수 없는 경우, 노드의 커널 버전을 NVMe 패키지가 있는 버전으로 업데이트해야 할 수 있습니다.


====
[role="tabbed-block"]
====
.RHEL 9
--
[source, console]
----
sudo yum install nvme-cli
sudo yum install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
.우분투
--
[source, console]
----
sudo apt install nvme-cli
sudo apt -y install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
====


== FC 도구

운영 체제에 맞는 명령을 사용하여 FC 도구를 설치하세요.

* FC PV와 함께 RHEL/Red Hat Enterprise Linux CoreOS(RHCOS)를 실행하는 작업자 노드를 사용하는 경우 다음을 지정합니다. `discard` StorageClass의 mountOption을 사용하여 인라인 공간 회수를 수행합니다. 참조하다 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["Red Hat 문서"^] .


[role="tabbed-block"]
====
.RHEL 8 이상
--
. 다음 시스템 패키지를 설치하세요:
+
[source, console]
----
sudo yum install -y lsscsi device-mapper-multipath
----
. 다중 경로 활성화:
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: 보장하다 `etc/multipath.conf` 포함하다 `find_multipaths no` 아래에 `defaults` .

. 확인하십시오 `multipathd` 실행 중입니다:
+
[source, console]
----
sudo systemctl enable --now multipathd
----


--
.우분투
--
. 다음 시스템 패키지를 설치하세요:
+
[source, console]
----
sudo apt-get install -y lsscsi sg3-utils multipath-tools scsitools
----
. 다중 경로 활성화:
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: 보장하다 `etc/multipath.conf` 포함하다 `find_multipaths no` 아래에 `defaults` .

. 확인하십시오 `multipath-tools` 활성화되어 실행 중입니다.
+
[source, console]
----
sudo systemctl status multipath-tools
----


--
====