---
sidebar: sidebar 
permalink: trident-docker/upgrade-uninstall-docker.html 
keywords: uninstall, Trident, trident for docker, docker, upgrade trident for docker 
summary: '사용 중인 볼륨에 영향을 주지 않고 Docker용 Trident 안전하게 업그레이드할 수 있습니다.  업그레이드 프로세스 동안 잠시 시간이 걸립니다. `docker volume` 플러그인에 대한 명령은 성공하지 못하고, 플러그인이 다시 실행될 때까지 애플리케이션은 볼륨을 마운트할 수 없습니다.  대부분의 경우 이는 몇 초 만에 끝납니다.' 
---
= Trident 업그레이드 또는 제거
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용 중인 볼륨에 영향을 주지 않고 Docker용 Trident 안전하게 업그레이드할 수 있습니다.  업그레이드 프로세스 동안 잠시 시간이 걸립니다. `docker volume` 플러그인에 대한 명령은 성공하지 못하고, 플러그인이 다시 실행될 때까지 애플리케이션은 볼륨을 마운트할 수 없습니다.  대부분의 경우 이는 몇 초 만에 끝납니다.



== 치받이

Docker용 Trident 업그레이드하려면 아래 단계를 수행하세요.

.단계
. 기존 볼륨을 나열하세요:
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----
. 플러그인을 비활성화하세요:
+
[listing]
----
docker plugin disable -f netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. 플러그인을 업그레이드하세요:
+
[listing]
----
docker plugin upgrade --skip-remote-check --grant-all-permissions netapp:latest netapp/trident-plugin:21.07
----
+

NOTE: Trident 의 18.01 릴리스는 nDVP를 대체합니다.  직접 업그레이드해야 합니다. `netapp/ndvp-plugin` 이미지를 `netapp/trident-plugin` 영상.

. 플러그인을 활성화하세요:
+
[listing]
----
docker plugin enable netapp:latest
----
. 플러그인이 활성화되어 있는지 확인하세요.
+
[listing]
----
docker plugin ls
ID                  NAME                DESCRIPTION                             ENABLED
7067f39a5df5        netapp:latest       Trident - NetApp Docker Volume Plugin   true
----
. 볼륨이 표시되는지 확인하세요.
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----



IMPORTANT: Trident 의 이전 버전(20.10 이전)에서 Trident 20.10 이상으로 업그레이드하는 경우 오류가 발생할 수 있습니다.  자세한 내용은 다음을 참조하세요.link:known-issues-docker.html["알려진 문제"^] .  오류가 발생하면 먼저 플러그인을 비활성화한 다음 플러그인을 제거한 다음 추가 구성 매개변수를 전달하여 필요한 Trident 버전을 설치해야 합니다. `docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json`



== 제거

Docker용 Trident 제거하려면 아래 단계를 수행하세요.

.단계
. 플러그인이 생성한 모든 볼륨을 제거합니다.
. 플러그인을 비활성화하세요:
+
[listing]
----
docker plugin disable netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. 플러그인을 제거하세요:
+
[listing]
----
docker plugin rm netapp:latest
----

