---
sidebar: sidebar 
permalink: trident-docker/volumes-docker.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume 
summary: '볼륨을 생성하려면 표준을 사용하세요. `docker volume` 필요한 경우 Trident 드라이버 이름을 지정하여 명령을 실행합니다.' 
---
= 볼륨 작업
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
표준을 사용하여 볼륨을 쉽게 생성, 복제 및 제거할 수 있습니다. `docker volume` 필요한 경우 Trident 드라이버 이름을 지정하여 명령을 실행합니다.



== 볼륨을 생성합니다

* 기본 이름을 사용하여 드라이버로 볼륨을 생성합니다.
+
[source, console]
----
docker volume create -d netapp --name firstVolume
----
* 특정 Trident 인스턴스로 볼륨을 생성합니다.
+
[source, console]
----
docker volume create -d ntap_bronze --name bronzeVolume
----
+

NOTE: 아무것도 지정하지 않으면link:volume-driver-options.html["옵션"^] 드라이버의 기본값이 사용됩니다.

* 기본 볼륨 크기를 재정의합니다. 드라이버를 사용하여 20GiB 볼륨을 생성하는 다음 예를 참조하세요.
+
[source, console]
----
docker volume create -d netapp --name my_vol --opt size=20G
----
+

TIP: 볼륨 크기는 선택적 단위(예: 10G, 20GB, 3TiB)가 포함된 정수 값을 포함하는 문자열로 표현됩니다.  단위를 지정하지 않으면 기본값은 G입니다. 크기 단위는 2의 거듭제곱(B, KiB, MiB, GiB, TiB) 또는 10의 거듭제곱(B, KB, MB, GB, TB)으로 표현할 수 있습니다.  약어 단위는 2의 거듭제곱을 사용합니다(G = GiB, T = TiB, …).





== 볼륨 제거

* 다른 Docker 볼륨과 마찬가지로 볼륨을 제거합니다.
+
[source, console]
----
docker volume rm firstVolume
----
+

IMPORTANT: 사용 시 `solidfire-san` 드라이버의 경우 위의 예에서는 볼륨을 삭제하고 제거합니다.



Docker용 Trident 업그레이드하려면 아래 단계를 수행하세요.



== 볼륨 복제

사용 시 `ontap-nas` , `ontap-san` , `solidfire-san` , 그리고 `gcp-cvs storage drivers` Trident 볼륨을 복제할 수 있습니다.  사용 시 `ontap-nas-flexgroup` 또는 `ontap-nas-economy` 드라이버, 복제가 지원되지 않습니다.  기존 볼륨에서 새 볼륨을 생성하면 새로운 스냅샷이 생성됩니다.

* 볼륨을 검사하여 스냅샷을 열거합니다.
+
[source, console]
----
docker volume inspect <volume_name>
----
* 기존 볼륨에서 새 볼륨을 만듭니다.  그러면 새로운 스냅샷이 생성됩니다.
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume>
----
* 볼륨의 기존 스냅샷에서 새 볼륨을 만듭니다.  이렇게 하면 새로운 스냅샷이 생성되지 않습니다.
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume> -o fromSnapshot=<source_snap_name>
----




=== 예

[source, console]
----
docker volume inspect firstVolume

[
  {
    "Driver": "ontap-nas",
    "Labels": null,
    "Mountpoint": "/var/lib/docker-volumes/ontap-nas/netappdvp_firstVolume",
    "Name": "firstVolume",
    "Options": {},
    "Scope": "global",
    "Status": {
      "Snapshots": [
        {
          "Created": "2017-02-10T19:05:00Z",
          "Name": "hourly.2017-02-10_1505"
        }
      ]
    }
  }
]

docker volume create -d ontap-nas --name clonedVolume -o from=firstVolume
clonedVolume

docker volume rm clonedVolume
docker volume create -d ontap-nas --name volFromSnap -o from=firstVolume -o fromSnapshot=hourly.2017-02-10_1505
volFromSnap

docker volume rm volFromSnap
----


== 외부에서 생성된 볼륨에 액세스

Trident 사용하는 컨테이너는 파티션이 없고 파일 시스템이 Trident 에서 지원되는 경우에만 외부에서 생성된 블록 장치(또는 해당 복제본)에 액세스할 수 있습니다(예: `ext4` -포맷됨 `/dev/sdc1` Trident 통해서는 접근할 수 없습니다.)
