---
sidebar: sidebar 
permalink: trident-managing-k8s/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: Trident 에 간편하게 접근할 수 있는 명령줄 유틸리티인 tridentctl에 대해 자세히 알아보세요. 
---
= tridentctl을 사용하여 Trident 관리
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그만큼 https://github.com/NetApp/trident/releases["Trident 설치 프로그램 번들"^] 포함 `tridentctl` Trident 에 간편하게 접근할 수 있는 명령줄 유틸리티입니다.  충분한 권한이 있는 Kubernetes 사용자는 이를 사용하여 Trident 설치하거나 Trident Pod가 포함된 네임스페이스를 관리할 수 있습니다.



== 명령 및 글로벌 플래그

당신은 실행할 수 있습니다 `tridentctl help` 사용 가능한 명령 목록을 얻으려면 `tridentctl` 또는 추가 `--help` 특정 명령에 대한 옵션과 플래그 목록을 얻으려면 해당 명령에 플래그를 추가합니다.

`tridentctl [command] [--optional-flag]`

Trident `tridentctl` 유틸리티는 다음 명령과 글로벌 플래그를 지원합니다.

.명령
[%collapsible]
====
`create`:: Trident 에 리소스를 추가합니다.
`delete`:: Trident 에서 하나 이상의 리소스를 제거합니다.
`get`:: Trident 에서 하나 이상의 리소스를 받으세요.
`help`:: 모든 명령에 대한 도움말.
`images`:: Trident 에 필요한 컨테이너 이미지 표를 인쇄하세요.
`import`:: 기존 리소스를 Trident 로 가져옵니다.
`install`:: Trident 설치하세요.
`logs`:: Trident 에서 로그를 인쇄합니다.
`send`:: Trident 에서 리소스를 보내세요.
`uninstall`:: Trident 제거합니다.
`update`:: Trident 에서 리소스를 수정합니다.
`update backend state`:: 백엔드 작업을 일시적으로 중단합니다.
`upgrade`:: Trident 의 리소스를 업그레이드하세요.
`version`:: Trident 버전을 인쇄하세요.


====
.글로벌 플래그
[%collapsible]
====
`-d`, `--debug`:: 디버그 출력.
`-h`, `--help`:: 도움말 `tridentctl` .
`-k`, `--kubeconfig string`:: 지정하세요 `KUBECONFIG` 로컬에서 명령을 실행하거나 한 Kubernetes 클러스터에서 다른 클러스터로 명령을 실행하는 경로입니다.
+
--

NOTE: 또는 다음을 내보낼 수 있습니다. `KUBECONFIG` 특정 Kubernetes 클러스터를 가리키고 문제를 해결하는 변수 `tridentctl` 해당 클러스터에 대한 명령입니다.

--
`-n`, `--namespace string`:: Trident 배포의 네임스페이스.
`-o`, `--output string`:: 출력 형식.  json|yaml|name|wide|ps 중 하나(기본값).
`-s`, `--server string`:: Trident REST 인터페이스의 주소/포트.
+
--

WARNING: Trident REST 인터페이스는 127.0.0.1(IPv4의 경우) 또는 [::1](IPv6의 경우)에서만 수신하고 서비스하도록 구성할 수 있습니다.

--


====


== 명령 옵션 및 플래그



=== 만들다

사용하다 `create` Trident 에 리소스를 추가하는 명령입니다.

`tridentctl create [option]`

옵션:: `backend`: Trident 에 백엔드를 추가합니다.




=== 삭제

사용하다 `delete` Trident 에서 하나 이상의 리소스를 제거하는 명령입니다.

`tridentctl delete [option]`

옵션:: `backend`: Trident 에서 하나 이상의 스토리지 백엔드를 삭제합니다.
`snapshot` : Trident 에서 하나 이상의 볼륨 스냅샷을 삭제합니다.
`storageclass` : Trident 에서 하나 이상의 스토리지 클래스를 삭제합니다.
`volume` : Trident 에서 하나 이상의 저장 볼륨을 삭제합니다.




=== 얻다

사용하다 `get` Trident 에서 하나 이상의 리소스를 가져오는 명령입니다.

`tridentctl get [option]`

옵션:: `backend`: Trident 에서 하나 이상의 스토리지 백엔드를 가져옵니다.
`snapshot` : Trident 에서 하나 이상의 스냅샷을 가져옵니다.
`storageclass` : Trident 에서 하나 이상의 스토리지 클래스를 받으세요.
`volume` : Trident 에서 한 권 이상의 책을 구입하세요.
깃발:: `-h`, `--help` : 볼륨에 대한 도움말.
`--parentOfSubordinate string` : 하위 소스 볼륨에 대한 쿼리를 제한합니다.
`--subordinateOf string` : 볼륨의 하위 항목으로 쿼리를 제한합니다.




=== 이미지

사용 `images` Trident 에 필요한 컨테이너 이미지 표를 인쇄하는 플래그입니다.

`tridentctl images [flags]`

깃발:: `-h`, `--help` : 이미지에 대한 도움말.
`-v` , `--k8s-version string` : Kubernetes 클러스터의 의미적 버전.




=== 수입량

사용하다 `import volume` 기존 볼륨을 Trident 로 가져오는 명령입니다.

`tridentctl import volume <backendName> <volumeName> [flags]`

별칭:: `volume`, `v`
깃발:: `-f`, `--filename string` : YAML 또는 JSON PVC 파일의 경로입니다.
`-h` , `--help` : 볼륨에 대한 도움말.
`--no-manage` : PV/PVC만 생성합니다.  볼륨 수명 주기 관리를 가정하지 마세요.




=== 설치하다

사용하다 `install` Trident 설치하기 위한 플래그입니다.

`tridentctl install [flags]`

깃발:: `--autosupport-image string`: Autosupport Telemetry를 위한 컨테이너 이미지(기본값 "netapp/trident autosupport:<current-version>").
`--autosupport-proxy string` : Autosupport Telemetry를 보내기 위한 프록시의 주소/포트입니다.
`--enable-node-prep` : 노드에 필요한 패키지를 설치해 보세요.
`--generate-custom-yaml` : 아무것도 설치하지 않고 YAML 파일을 생성합니다.
`-h` , `--help` : 설치에 대한 도움말.
`--http-request-timeout` : Trident 컨트롤러의 REST API에 대한 HTTP 요청 시간 초과를 재정의합니다(기본값 1분 30초).
`--image-registry string` : 내부 이미지 레지스트리의 주소/포트.
`--k8s-timeout duration` : 모든 Kubernetes 작업에 대한 시간 초과(기본값 3분 0초).
`--kubelet-dir string` : kubelet의 내부 상태의 호스트 위치(기본값 "/var/lib/kubelet").
`--log-format string` : Trident 로깅 형식(텍스트, JSON)(기본값은 "텍스트")입니다.
`--node-prep` : Trident 지정된 데이터 저장 프로토콜을 사용하여 볼륨을 관리하도록 Kubernetes 클러스터의 노드를 준비할 수 있도록 합니다.  *현재, `iscsi` 지원되는 유일한 값입니다.  OpenShift 4.19부터 이 기능을 지원하는 최소 Trident 버전은 25.06.1입니다.*
`--pv string` : Trident 에서 사용되는 레거시 PV의 이름으로, 이것이 존재하지 않도록 합니다(기본값은 "trident").
`--pvc string` : Trident 에서 사용하는 레거시 PVC의 이름으로, 이것이 존재하지 않도록 합니다(기본값은 "trident").
`--silence-autosupport` : NetApp 에 ​​자동 지원 번들을 자동으로 보내지 않습니다(기본값은 true).
`--silent` : 설치 중에 대부분의 출력을 비활성화합니다.
`--trident-image string` : 설치할 Trident 이미지입니다.
`--k8s-api-qps` : Kubernetes API 요청에 대한 초당 쿼리 수(QPS) 제한(기본값 100, 선택 사항).
`--use-custom-yaml` : 설치 디렉토리에 있는 기존 YAML 파일을 사용합니다.
`--use-ipv6` : Trident 통신에 IPv6를 사용합니다.




=== 통나무

사용 `logs` Trident 에서 로그를 인쇄하기 위한 플래그입니다.

`tridentctl logs [flags]`

깃발:: `-a`, `--archive` : 달리 지정하지 않는 한 모든 로그를 포함하는 지원 보관소를 만듭니다.
`-h` , `--help` : 로그에 대한 도움말.
`-l` , `--log string` : Trident 로그를 표시합니다.  trident|auto|trident-operator|all 중 하나(기본값은 "auto").
`--node string` : 노드 포드 로그를 수집할 Kubernetes 노드 이름입니다.
`-p` , `--previous` : 이전 컨테이너 인스턴스에 대한 로그가 있으면 가져옵니다.
`--sidecars` : 사이드카 컨테이너의 통나무를 가져오세요.




=== 보내다

사용하다 `send` Trident 에서 리소스를 보내는 명령입니다.

`tridentctl send [option]`

옵션:: `autosupport`: NetApp 에 ​​Autosupport 아카이브를 보냅니다.




=== 제거

사용 `uninstall` Trident 제거하기 위한 플래그입니다.

`tridentctl uninstall [flags]`

깃발:: `-h, --help`: 제거에 대한 도움말.
`--silent` : 설치 제거 시 대부분의 출력을 비활성화합니다.




=== 업데이트

사용하다 `update` Trident 에서 리소스를 수정하는 명령입니다.

`tridentctl update [option]`

옵션:: `backend`: Trident 에서 백엔드를 업데이트합니다.




=== 백엔드 상태 업데이트

사용하다 `update backend state` 백엔드 작업을 일시 중단하거나 재개하는 명령입니다.

`tridentctl update backend state <backend-name> [flag]`

.고려할 사항
* TridentBackendConfig(tbc)를 사용하여 백엔드를 생성한 경우 백엔드를 사용하여 업데이트할 수 없습니다. `backend.json` 파일.
* 만약 `userState` tbc에 설정되어 있으므로 다음을 사용하여 수정할 수 없습니다. `tridentctl update backend state <backend-name> --user-state suspended/normal` 명령.
* 설정 기능을 다시 얻으려면 `userState` tbc를 통해 설정된 후 tridentctl을 통해 `userState` 해당 필드는 tbc에서 제거되어야 합니다.  이것은 다음을 사용하여 수행할 수 있습니다. `kubectl edit tbc` 명령.  후에 `userState` 필드가 제거되면 다음을 사용할 수 있습니다. `tridentctl update backend state` 변경 명령 `userState` 백엔드의.
* 사용하다 `tridentctl update backend state` 변경하려면 `userState` .  또한 업데이트할 수 있습니다 `userState` 사용 중 `TridentBackendConfig` 또는 `backend.json` 파일; 이렇게 하면 백엔드가 완전히 다시 초기화되므로 시간이 많이 걸릴 수 있습니다.
+
깃발:: `-h`, `--help` : 백엔드 상태에 대한 도움말.
`--user-state` : 설정 `suspended` 백엔드 작업을 일시 중지합니다.  로 설정 `normal` 백엔드 작업을 재개합니다.  설정 시 `suspended` :


* `AddVolume`그리고 `Import Volume` 일시 정지되었습니다.
* `CloneVolume`, `ResizeVolume` , `PublishVolume` , `UnPublishVolume` , `CreateSnapshot` , `GetSnapshot` , `RestoreSnapshot` , `DeleteSnapshot` , `RemoveVolume` , `GetVolumeExternal` , `ReconcileNodeAccess` 계속 이용 가능합니다.


다음을 사용하여 백엔드 상태를 업데이트할 수도 있습니다. `userState` 백엔드 구성 파일의 필드 `TridentBackendConfig` 또는 `backend.json` .  자세한 내용은 다음을 참조하세요.link:../trident-use/backend_options.html["백엔드 관리를 위한 옵션"] 그리고link:../trident-use/backend_ops_kubectl.html["kubectl을 사용하여 백엔드 관리 수행"] .

*예:*

[role="tabbed-block"]
====
.JSON
--
다음 단계에 따라 업데이트하세요. `userState` 사용하여 `backend.json` 파일:

. 편집하다 `backend.json` 포함할 파일 `userState` 값이 '일시 중단'으로 설정된 필드입니다.
. 다음을 사용하여 백엔드를 업데이트합니다. `tridentctl update backend` 명령 및 업데이트 경로 `backend.json` 파일.
+
*예*: `tridentctl update backend  -f /<path to backend JSON file>/backend.json -n trident`



[listing]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "<redacted>",
  "svm": "nas-svm",
  "backendName": "customBackend",
  "username": "<redacted>",
  "password": "<redacted>",
  "userState": "suspended"
}

----
--
.YAML
--
tbc가 적용된 후에는 다음을 사용하여 tbc를 편집할 수 있습니다. `kubectl edit <tbc-name> -n <namespace>` 명령.  다음 예제에서는 다음을 사용하여 백엔드 상태를 일시 중단으로 업데이트합니다. `userState: suspended` 옵션:

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-ontap-nas
spec:
  version: 1
  backendName: customBackend
  storageDriverName: ontap-nas
  managementLIF: <redacted>
  svm: nas-svm
  userState: suspended
  credentials:
    name: backend-tbc-ontap-nas-secret
----
--
====


=== 버전

사용 `version` 버전을 인쇄하기 위한 플래그 `tridentctl` 그리고 Trident 서비스를 운영하고 있습니다.

`tridentctl version [flags]`

깃발:: `--client`: 클라이언트 버전만 해당(서버 필요 없음).
`-h, --help` : 버전에 대한 도움말.




== 플러그인 지원

Tridentctl은 kubectl과 유사한 플러그인을 지원합니다.  Tridentctl은 플러그인 바이너리 파일 이름이 "tridentctl-<플러그인>" 체계를 따르고 바이너리가 PATH 환경 변수에 나열된 폴더에 있는 경우 플러그인을 감지합니다.  감지된 모든 플러그인은 tridentctl 도움말의 플러그인 섹션에 나열되어 있습니다.  선택적으로 환경 변수 TRIDENTCTL_PLUGIN_PATH에 플러그인 폴더를 지정하여 검색을 제한할 수도 있습니다(예: `TRIDENTCTL_PLUGIN_PATH=~/tridentctl-plugins/` ).  변수를 사용하면 tridenctl은 지정된 폴더에서만 검색합니다.
