---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-trident.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: Trident 4개월 주기로 출시되며, 매년 3개의 주요 릴리스를 제공합니다.  각각의 새로운 릴리스는 이전 릴리스를 기반으로 구축되어 새로운 기능과 성능 향상, 버그 수정 및 개선 사항을 제공합니다.  Trident 의 새로운 기능을 활용하려면 최소한 1년에 한 번 업그레이드하는 것이 좋습니다. 
---
= Trident 업그레이드
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident 24.02 릴리스부터 4개월 릴리스 주기를 따르며, 매년 3개의 주요 릴리스를 제공합니다.  각각의 새로운 릴리스는 이전 릴리스를 기반으로 하며 새로운 기능, 성능 향상, 버그 수정 및 개선 사항을 제공합니다.  Trident 의 새로운 기능을 활용하려면 최소한 1년에 한 번 업그레이드하는 것이 좋습니다.



== 업그레이드 전 고려 사항

Trident 의 최신 릴리스로 업그레이드할 때 다음 사항을 고려하세요.

* 주어진 Kubernetes 클러스터의 모든 네임스페이스에 Trident 인스턴스는 하나만 설치되어야 합니다.
* Trident 23.07 이상에서는 v1 볼륨 스냅샷이 필요하며 더 이상 알파 또는 베타 스냅샷을 지원하지 않습니다.
* Google Cloud에 대한 Cloud Volumes Service 생성한 경우link:../trident-use/gcp.html#learn-about-trident-support-for-cloud-volumes-service-for-google-cloud["CVS 서비스 유형"] , 백엔드 구성을 업데이트하여 사용해야 합니다. `standardsw` 또는 `zoneredundantstandardsw` Trident 23.01에서 업그레이드할 때의 서비스 수준.  업데이트 실패 `serviceLevel` 백엔드에서는 볼륨이 실패할 수 있습니다. 참조하다 link:../trident-use/gcp.html#cvs-service-type-examples["CVS 서비스 유형 샘플"] 자세한 내용은.
* 업그레이드할 때 다음을 제공하는 것이 중요합니다. `parameter.fsType` ~에 `StorageClasses` Trident 에서 사용됨.  삭제하고 다시 만들 수 있습니다 `StorageClasses` 기존 볼륨을 방해하지 않고.
+
** 이는 시행을 위한 **요구사항**입니다. https://kubernetes.io/docs/tasks/configure-pod-container/security-context/["보안 컨텍스트"^] SAN 볼륨의 경우.
** https://github.com/NetApp/trident/tree/master/trident-installer/sample-input [sample input^] 디렉토리에는 https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-basic.yaml.templ 과 같은 예가 포함되어 있습니다.[`storage-class-basic.yaml.templ` ^] 및 링크: https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-bronze-default.yaml[`storage-class-bronze-default.yaml` ^].
** 자세한 내용은 다음을 참조하세요.link:../trident-rn.html["알려진 문제"] .






== 1단계: 버전 선택

Trident 버전은 날짜 기반을 따릅니다. `YY.MM` 명명 규칙에 따르면 "YY"는 연도의 마지막 두 자리이고 "MM"은 월입니다.  Dot 릴리스는 다음을 따릅니다. `YY.MM.X` 여기서 "X"는 패치 수준입니다.  업그레이드할 버전은 업그레이드하려는 버전에 따라 선택됩니다.

* 설치된 버전의 4개 릴리스 창 내에 있는 모든 대상 릴리스로 직접 업그레이드를 수행할 수 있습니다.  예를 들어, 24.06(또는 모든 24.06 dot 릴리스)에서 25.06으로 직접 업그레이드할 수 있습니다.
* 4개 릴리스 창 이외의 릴리스에서 업그레이드하는 경우 여러 단계로 업그레이드하세요.  업그레이드 지침을 사용하세요.link:../earlier-versions.html["이전 버전"] 4개 릴리스 창에 맞는 최신 릴리스로 업그레이드합니다.  예를 들어, 23.07을 실행 중이고 25.06으로 업그레이드하려는 경우:
+
.. 23.07에서 24.06으로 첫 번째 업그레이드.
.. 그런 다음 24.06에서 25.06으로 업그레이드하세요.





NOTE: OpenShift Container Platform에서 Trident 연산자를 사용하여 업그레이드하는 경우 Trident 21.01.1 이상으로 업그레이드해야 합니다.  21.01.0과 함께 출시된 Trident 연산자에는 21.01.1에서 수정된 알려진 문제가 포함되어 있습니다.  자세한 내용은 다음을 참조하세요. https://github.com/NetApp/trident/issues/517["GitHub의 이슈 세부 정보"^] .



== 2단계: 원래 설치 방법 확인

Trident 처음 설치하는 데 사용한 버전을 확인하려면 다음을 수행하세요.

. 사용 `kubectl get pods -n trident` 꼬투리를 조사하기 위해서.
+
** 운영자 포드가 없는 경우 Trident 설치되었습니다. `tridentctl` .
** 운영자 포드가 있는 경우, Trident 운영자를 수동으로 사용하거나 Helm을 사용하여 Trident 설치했습니다.


. 운영자 포드가 있는 경우 사용하세요 `kubectl describe torc` Helm을 사용하여 Trident 설치되었는지 확인합니다.
+
** Helm 레이블이 있으면 Helm을 사용하여 Trident 설치되었다는 의미입니다.
** Helm 레이블이 없으면 Trident 연산자를 사용하여 Trident 수동으로 설치되었습니다.






== 3단계: 업그레이드 방법 선택

일반적으로 초기 설치에 사용한 것과 동일한 방법을 사용하여 업그레이드해야 하지만link:../trident-get-started/kubernetes-deploy.html#moving-between-installation-methods["설치 방법 간 이동"] .  Trident 업그레이드하는 데는 두 가지 옵션이 있습니다.

* link:upgrade-operator.html["Trident 연산자를 사용하여 업그레이드"]
+

TIP: 검토해 보시기 바랍니다link:upgrade-operator-overview.html["운영자 업그레이드 워크플로 이해"] 운영자와 함께 업그레이드하기 전에.

* 

