---
sidebar: sidebar 
permalink: trident-use/anf-prep.html 
keywords: trident backend, azure netapp files, smb volumes, smb, windows, active directory, csi proxy, aks, managed identities 
summary: Azure NetApp Files 백엔드를 구성하기 전에 다음 요구 사항이 충족되는지 확인해야 합니다. 
---
= Azure NetApp Files 백엔드 구성을 준비합니다.
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Azure NetApp Files 백엔드를 구성하기 전에 다음 요구 사항이 충족되는지 확인해야 합니다.



== NFS 및 SMB 볼륨에 대한 필수 구성 요소

Azure NetApp Files 처음 사용하거나 새로운 위치에서 사용하는 경우 Azure NetApp Files를 설정하고 NFS 볼륨을 생성하기 위해 일부 초기 구성이 필요합니다. 참조하다 https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-quickstart-set-up-account-create-volumes["Azure: Azure NetApp Files 설정 및 NFS 볼륨 생성"^] .

구성하고 사용하려면 https://azure.microsoft.com/en-us/services/netapp/["Azure NetApp Files"^] 백엔드에는 다음이 필요합니다.

[NOTE]
====
* `subscriptionID`, `tenantID` , `clientID` , `location` , 그리고 `clientSecret` AKS 클러스터에서 관리형 ID를 사용하는 경우 선택 사항입니다.
* `tenantID`, `clientID` , 그리고 `clientSecret` AKS 클러스터에서 클라우드 ID를 사용하는 경우 선택 사항입니다.


====
* 수용 인원 풀. 참조하다link:https://learn.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-set-up-capacity-pool["Microsoft: Azure NetApp Files 대한 용량 풀 만들기"^] .
* Azure NetApp Files 에 위임된 서브넷입니다. 참조하다link:https://learn.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-delegate-subnet["Microsoft: Azure NetApp Files 에 서브넷 위임"^] .
* `subscriptionID`Azure NetApp Files 활성화된 Azure 구독에서.
* `tenantID`, `clientID` , 그리고 `clientSecret` 에서link:https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal["앱 등록"^] Azure NetApp Files 서비스에 대한 충분한 권한이 있는 Azure Active Directory에 있습니다.  앱 등록에는 다음 중 하나를 사용해야 합니다.
+
** 소유자 또는 기여자 역할link:https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles["Azure에서 미리 정의됨"^] .
** 에이link:https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles-portal["사용자 정의 기여자 역할"] 구독 수준에서(`assignableScopes` ) Trident 에 필요한 것으로만 제한된 다음 권한이 있습니다.  사용자 정의 역할을 만든 후,link:https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal["Azure Portal을 사용하여 역할 할당"^] .
+
.사용자 정의 기여자 역할
[%collapsible]
====
[source, JSON]
----
{
  "id": "/subscriptions/<subscription-id>/providers/Microsoft.Authorization/roleDefinitions/<role-definition-id>",
  "properties": {
    "roleName": "custom-role-with-limited-perms",
    "description": "custom role providing limited permissions",
    "assignableScopes": [
      "/subscriptions/<subscription-id>"
    ],
    "permissions": [
      {
        "actions": [
          "Microsoft.NetApp/netAppAccounts/capacityPools/read",
          "Microsoft.NetApp/netAppAccounts/capacityPools/write",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/read",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/write",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/delete",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots/read",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots/write",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots/delete",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/MountTargets/read",
          "Microsoft.Network/virtualNetworks/read",
          "Microsoft.Network/virtualNetworks/subnets/read",
          "Microsoft.Features/featureProviders/subscriptionFeatureRegistrations/read",
          "Microsoft.Features/featureProviders/subscriptionFeatureRegistrations/write",
          "Microsoft.Features/featureProviders/subscriptionFeatureRegistrations/delete",
          "Microsoft.Features/features/read",
          "Microsoft.Features/operations/read",
          "Microsoft.Features/providers/features/read",
          "Microsoft.Features/providers/features/register/action",
          "Microsoft.Features/providers/features/unregister/action",
          "Microsoft.Features/subscriptionFeatureRegistrations/read"
        ],
        "notActions": [],
        "dataActions": [],
        "notDataActions": []
      }
    ]
  }
}
----
====


* Azure `location` 적어도 하나 이상 포함 https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-delegate-subnet["위임된 서브넷"^] .  Trident 22.01부터 `location` 매개변수는 백엔드 구성 파일의 최상위에 있는 필수 필드입니다.  가상 풀에 지정된 위치 값은 무시됩니다.
* 사용하려면 `Cloud Identity` , 얻으세요 `client ID` 에서 https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-manage-user-assigned-managed-identities["사용자가 할당한 관리 ID"^] 그리고 해당 ID를 지정하세요 `azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx` .




== SMB 볼륨에 대한 추가 요구 사항

SMB 볼륨을 생성하려면 다음이 필요합니다.

* Active Directory가 구성되고 Azure NetApp Files 에 연결되었습니다. 참조하다link:https://learn.microsoft.com/en-us/azure/azure-netapp-files/create-active-directory-connections["Microsoft: Azure NetApp Files 대한 Active Directory 연결 만들기 및 관리"^] .
* Linux 컨트롤러 노드와 Windows Server 2022를 실행하는 하나 이상의 Windows 워커 노드가 있는 Kubernetes 클러스터입니다.  Trident Windows 노드에서 실행되는 Pod에 마운트된 SMB 볼륨만 지원합니다.
* Azure NetApp Files Active Directory에 인증할 수 있도록 Active Directory 자격 증명이 포함된 Trident 비밀이 하나 이상 있어야 합니다.  비밀을 생성하려면 `smbcreds` :
+
[listing]
----
kubectl create secret generic smbcreds --from-literal username=user --from-literal password='password'
----
* Windows 서비스로 구성된 CSI 프록시.  구성하려면 `csi-proxy` , 참조하다link:https://github.com/kubernetes-csi/csi-proxy["GitHub: CSI 프록시"^] 또는link:https://github.com/Azure/aks-engine/blob/master/docs/topics/csi-proxy-windows.md["GitHub: Windows용 CSI 프록시"^] Windows에서 실행되는 Kubernetes 노드의 경우.

