---
sidebar: sidebar 
permalink: trident-use/element.html 
keywords: trident backend, solidfire, netapp hci, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Trident 설치로 Element 백엔드를 만들고 사용하는 방법에 대해 알아보세요. 
---
= NetApp HCI 또는 SolidFire 백엔드 구성
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident 설치로 Element 백엔드를 만들고 사용하는 방법을 알아보세요.



== 요소 드라이버 세부 정보

Trident 다음을 제공합니다. `solidfire-san` 클러스터와 통신하기 위한 저장 드라이버.  지원되는 액세스 모드는 다음과 같습니다: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

그만큼 `solidfire-san` 저장 드라이버는 _파일_ 및 _블록_ 볼륨 모드를 지원합니다.  를 위해 `Filesystem` volumeMode, Trident 볼륨을 생성하고 파일 시스템을 생성합니다.  파일 시스템 유형은 StorageClass에 의해 지정됩니다.

[cols="5"]
|===
| 운전사 | 규약 | 볼륨모드 | 지원되는 액세스 모드 | 지원되는 파일 시스템 


| `solidfire-san`  a| 
iSCSI
 a| 
차단하다
 a| 
RWO, ROX, RWX, RWOP
 a| 
파일 시스템이 없습니다.  원시 블록 장치.



| `solidfire-san`  a| 
iSCSI
 a| 
파일 시스템
 a| 
RWO, RWOP
 a| 
`xfs`, `ext3` , `ext4`

|===


== 시작하기 전에

Element 백엔드를 생성하려면 다음이 필요합니다.

* Element 소프트웨어를 실행하는 지원되는 저장 시스템입니다.
* 볼륨을 관리할 수 있는 NetApp HCI/ SolidFire 클러스터 관리자 또는 테넌트 사용자에 대한 자격 증명입니다.
* 모든 Kubernetes 워커 노드에는 적절한 iSCSI 도구가 설치되어 있어야 합니다. 참조하다link:../trident-use/worker-node-prep.html["워커 노드 준비 정보"] .




== 백엔드 구성 옵션

백엔드 구성 옵션은 다음 표를 참조하세요.

[cols="3"]
|===
| 매개변수 | 설명 | 기본 


| `version` |  | 항상 1 


| `storageDriverName` | 저장 드라이버의 이름 | 항상 "solidfire-san" 


| `backendName` | 사용자 정의 이름 또는 스토리지 백엔드 | "solidfire_" + 스토리지(iSCSI) IP 주소 


| `Endpoint` | 테넌트 자격 증명을 사용한 SolidFire 클러스터용 MVIP |  


| `SVIP` | 스토리지(iSCSI) IP 주소 및 포트 |  


| `labels` | 볼륨에 적용할 임의의 JSON 형식 레이블 집합입니다. | "" 


| `TenantName` | 사용할 테넌트 이름(찾을 수 없는 경우 생성) |  


| `InitiatorIFace` | iSCSI 트래픽을 특정 호스트 인터페이스로 제한 | "기본" 


| `UseCHAP` | CHAP를 사용하여 iSCSI를 인증합니다.  Trident CHAP를 사용합니다. | true 


| `AccessGroups` | 사용할 액세스 그룹 ID 목록 | "trident"라는 액세스 그룹의 ID를 찾습니다. 


| `Types` | QoS 사양 |  


| `limitVolumeSize` | 요청된 볼륨 크기가 이 값보다 크면 프로비저닝에 실패합니다. | "" (기본적으로 적용되지 않음) 


| `debugTraceFlags` | 문제 해결 시 사용할 디버그 플래그입니다.  예를 들어, {"api":false, "method":true} | 널 
|===

WARNING: 사용하지 마십시오 `debugTraceFlags` 문제 해결을 위해 자세한 로그 덤프가 필요한 경우가 아니면요.



== 예 1: 백엔드 구성 `solidfire-san` 3가지 볼륨 유형을 갖춘 드라이버

이 예제에서는 CHAP 인증을 사용하고 특정 QoS 보장을 갖춘 세 가지 볼륨 유형을 모델링하는 백엔드 파일을 보여줍니다.  그러면 각각을 사용하기 위해 저장소 클래스를 정의할 가능성이 가장 높습니다. `IOPS` 저장 클래스 매개변수.

[source, yaml]
----
---
version: 1
storageDriverName: solidfire-san
Endpoint: https://<user>:<password>@<mvip>/json-rpc/8.0
SVIP: <svip>:3260
TenantName: <tenant>
labels:
  k8scluster: dev1
  backend: dev1-element-cluster
UseCHAP: true
Types:
  - Type: Bronze
    Qos:
      minIOPS: 1000
      maxIOPS: 2000
      burstIOPS: 4000
  - Type: Silver
    Qos:
      minIOPS: 4000
      maxIOPS: 6000
      burstIOPS: 8000
  - Type: Gold
    Qos:
      minIOPS: 6000
      maxIOPS: 8000
      burstIOPS: 10000
----


== 예 2: 백엔드 및 스토리지 클래스 구성 `solidfire-san` 가상 풀이 있는 드라이버

이 예에서는 가상 풀과 이를 참조하는 StorageClass로 구성된 백엔드 정의 파일을 보여줍니다.

Trident 프로비저닝 시 스토리지 풀에 있는 레이블을 백엔드 스토리지 LUN에 복사합니다.  편의를 위해 스토리지 관리자는 가상 풀별로 레이블을 정의하고 레이블별로 볼륨을 그룹화할 수 있습니다.

아래에 표시된 샘플 백엔드 정의 파일에서는 모든 스토리지 풀에 대해 특정 기본값이 설정되어 있습니다. `type` 실버에서.  가상 풀은 다음에 정의됩니다. `storage` 부분.  이 예에서 일부 스토리지 풀은 자체 유형을 설정하고, 일부 풀은 위에 설정된 기본값을 재정의합니다.

[source, yaml]
----
---
version: 1
storageDriverName: solidfire-san
Endpoint: https://<user>:<password>@<mvip>/json-rpc/8.0
SVIP: <svip>:3260
TenantName: <tenant>
UseCHAP: true
Types:
  - Type: Bronze
    Qos:
      minIOPS: 1000
      maxIOPS: 2000
      burstIOPS: 4000
  - Type: Silver
    Qos:
      minIOPS: 4000
      maxIOPS: 6000
      burstIOPS: 8000
  - Type: Gold
    Qos:
      minIOPS: 6000
      maxIOPS: 8000
      burstIOPS: 10000
type: Silver
labels:
  store: solidfire
  k8scluster: dev-1-cluster
region: us-east-1
storage:
  - labels:
      performance: gold
      cost: "4"
    zone: us-east-1a
    type: Gold
  - labels:
      performance: silver
      cost: "3"
    zone: us-east-1b
    type: Silver
  - labels:
      performance: bronze
      cost: "2"
    zone: us-east-1c
    type: Bronze
  - labels:
      performance: silver
      cost: "1"
    zone: us-east-1d


----
다음 StorageClass 정의는 위의 가상 풀을 참조합니다.  를 사용하여 `parameters.selector` 필드에서 각 StorageClass는 볼륨을 호스팅하는 데 사용할 수 있는 가상 풀을 호출합니다.  볼륨에는 선택한 가상 풀에 정의된 측면이 있습니다.

첫 번째 StorageClass(`solidfire-gold-four` )은 첫 번째 가상 풀에 매핑됩니다.  이것은 골드 성능을 제공하는 유일한 풀입니다. `Volume Type QoS` 금의.  마지막 StorageClass(`solidfire-silver` )은 실버 성능을 제공하는 모든 스토리지 풀을 호출합니다.  Trident 어떤 가상 풀을 선택할지 결정하고 저장 요구 사항이 충족되는지 확인합니다.

[source, yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: solidfire-gold-four
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=gold; cost=4
  fsType: ext4

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: solidfire-silver-three
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=silver; cost=3
  fsType: ext4

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: solidfire-bronze-two
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=bronze; cost=2
  fsType: ext4

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: solidfire-silver-one
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=silver; cost=1
  fsType: ext4

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: solidfire-silver
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=silver
  fsType: ext4
----


== 더 많은 정보를 찾아보세요

* link:../trident-concepts/vol-access-groups.html["볼륨 액세스 그룹"^]

