---
sidebar: sidebar 
permalink: trident-use/gcnv.html 
keywords: trident backend, google cloud netapp volumes, nfs volumes, nfs, drivers, access modes, rwo, rwx, rwp, rwop, file system, gke, cloud identity, google cloud 
summary:  
---
= Google Cloud NetApp Volumes 백엔드 구성
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이제 Google Cloud NetApp Volumes Trident 의 백엔드로 구성할 수 있습니다.  Google Cloud NetApp Volumes 백엔드를 사용하여 NFS 및 SMB 볼륨을 연결할 수 있습니다.



== Google Cloud NetApp Volumes 드라이버 세부 정보

Trident 다음을 제공합니다. `google-cloud-netapp-volumes` 클러스터와 통신하는 드라이버.  지원되는 액세스 모드는 다음과 같습니다: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| 운전사 | 규약 | 볼륨모드 | 지원되는 액세스 모드 | 지원되는 파일 시스템 


| `google-cloud-netapp-volumes`  a| 
NFS SMB
 a| 
파일 시스템
 a| 
RWO, ROX, RWX, RWOP
 a| 
`nfs`, `smb`

|===


== GKE용 클라우드 ID

클라우드 ID를 사용하면 Kubernetes 포드가 명시적인 Google Cloud 자격 증명을 제공하는 대신 워크로드 ID로 인증하여 Google Cloud 리소스에 액세스할 수 있습니다.

Google Cloud에서 클라우드 ID를 활용하려면 다음이 필요합니다.

* GKE를 사용하여 배포된 Kubernetes 클러스터.
* GKE 클러스터에 구성된 워크로드 ID와 노드 풀에 구성된 GKE 메타데이터 서버.
* Google Cloud NetApp Volumes 관리자(roles/netapp.admin) 역할 또는 사용자 지정 역할이 있는 GCP 서비스 계정.
* "GCP"를 지정하는 cloudProvider와 새로운 GCP 서비스 계정을 지정하는 cloudIdentity를 포함하는 Trident 설치되었습니다.  아래에 예를 들어보겠습니다.
+
[role="tabbed-block"]
====
.Trident 연산자
--
Trident 연산자를 사용하여 Trident 설치하려면 다음을 편집하세요. `tridentorchestrator_cr.yaml` 설정하다 `cloudProvider` 에게 `"GCP"` 그리고 설정하다 `cloudIdentity` 에게 `iam.gke.io/gcp-service-account: \cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com` .

예를 들어:

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "GCP"
  cloudIdentity: 'iam.gke.io/gcp-service-account: cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com'
----
--
.지배
--
다음 환경 변수를 사용하여 *cloud-provider (CP)* 및 *cloud-identity (CI)* 플래그의 값을 설정합니다.

`export CP="GCP"`
`export ANNOTATION="'iam.gke.io/gcp-service-account: \cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com'"`

다음 예제에서는 Trident 설치하고 설정합니다. `cloudProvider` 환경 변수를 사용하여 GCP에 `$CP` 그리고 설정합니다 `cloudIdentity` 환경 변수 사용 `$ANNOTATION` :

[listing]
----
helm install trident trident-operator-100.6.0.tgz --set cloudProvider=$CP --set cloudIdentity="$ANNOTATION"
----
--
.<code>트라이던트ctl</code>
--
다음 환경 변수를 사용하여 *클라우드 공급자* 및 *클라우드 ID* 플래그의 값을 설정합니다.

`export CP="GCP"`
`export ANNOTATION="'iam.gke.io/gcp-service-account: \cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com'"`

다음 예제에서는 Trident 설치하고 설정합니다. `cloud-provider` 플래그를 `$CP` , 그리고 `cloud-identity` 에게 `$ANNOTATION` :

[listing]
----
tridentctl install --cloud-provider=$CP --cloud-identity="$ANNOTATION" -n trident
----
--
====

