---
sidebar: sidebar 
permalink: trident-use/manage-stor-class.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes 
summary: 기존 스토리지 클래스를 보고, 기본 스토리지 클래스를 설정하고, 스토리지 클래스 백엔드를 식별하고, 스토리지 클래스를 삭제할 수 있습니다. 
---
= 스토리지 클래스 관리
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 스토리지 클래스를 보고, 기본 스토리지 클래스를 설정하고, 스토리지 클래스 백엔드를 식별하고, 스토리지 클래스를 삭제할 수 있습니다.



== 기존 스토리지 클래스 보기

* 기존 Kubernetes 스토리지 클래스를 보려면 다음 명령을 실행하세요.


[listing]
----
kubectl get storageclass
----
* Kubernetes 스토리지 클래스 세부 정보를 보려면 다음 명령을 실행하세요.


[listing]
----
kubectl get storageclass <storage-class> -o json
----
* Trident의 동기화된 스토리지 클래스를 보려면 다음 명령을 실행하세요.


[listing]
----
tridentctl get storageclass
----
* Trident의 동기화된 스토리지 클래스 세부 정보를 보려면 다음 명령을 실행하세요.


[listing]
----
tridentctl get storageclass <storage-class> -o json
----


== 기본 저장소 클래스 설정

Kubernetes 1.6에서는 기본 스토리지 클래스를 설정하는 기능이 추가되었습니다.  이는 사용자가 PVC(영구 볼륨 클레임)에서 영구 볼륨을 지정하지 않은 경우 영구 볼륨을 프로비저닝하는 데 사용되는 스토리지 클래스입니다.

* 주석을 설정하여 기본 저장 클래스를 정의합니다. `storageclass.kubernetes.io/is-default-class` 저장 클래스 정의에서 true로 설정합니다.  사양에 따르면, 다른 값이나 주석이 없는 경우 거짓으로 해석됩니다.
* 다음 명령을 사용하여 기존 스토리지 클래스를 기본 스토리지 클래스로 구성할 수 있습니다.


[listing]
----
kubectl patch storageclass <storage-class-name> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
* 마찬가지로 다음 명령을 사용하여 기본 저장소 클래스 주석을 제거할 수 있습니다.


[listing]
----
kubectl patch storageclass <storage-class-name> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
Trident 설치 프로그램 번들에는 이 주석이 포함된 예도 있습니다.


NOTE: 클러스터에는 한 번에 하나의 기본 스토리지 클래스만 있어야 합니다.  Kubernetes는 기술적으로 두 개 이상을 갖는 것을 막지는 않지만, 기본 스토리지 클래스가 전혀 없는 것처럼 동작합니다.



== 스토리지 클래스의 백엔드 식별

이는 JSON으로 답할 수 있는 질문 종류의 예입니다. `tridentctl` Trident 백엔드 객체에 대한 출력.  이것은 다음을 사용합니다 `jq` 먼저 설치해야 할 유틸리티가 있습니다.

[listing]
----
tridentctl get storageclass -o json | jq  '[.items[] | {storageClass: .Config.name, backends: [.storage]|unique}]'
----


== 스토리지 클래스 삭제

Kubernetes에서 스토리지 클래스를 삭제하려면 다음 명령을 실행하세요.

[listing]
----
kubectl delete storageclass <storage-class>
----
`<storage-class>`저장 클래스로 대체해야 합니다.

이 스토리지 클래스를 통해 생성된 모든 영구 볼륨은 변경되지 않으며 Trident 계속해서 이를 관리합니다.


NOTE: Trident 공백을 강화합니다. `fsType` 그것이 만들어내는 볼륨 때문에요.  iSCSI 백엔드의 경우 다음을 적용하는 것이 좋습니다. `parameters.fsType` StorageClass에서.  기존 StorageClass를 삭제하고 다시 생성해야 합니다. `parameters.fsType` 지정된.
