---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: ONTAP SAN 드라이버를 사용하여 ONTAP 백엔드를 구성하는 방법에 대해 알아보세요. 
---
= ONTAP SAN 드라이버 개요
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 및 Cloud Volumes ONTAP SAN 드라이버를 사용하여 ONTAP 백엔드를 구성하는 방법에 대해 알아보세요.



== ONTAP SAN 드라이버 세부 정보

Trident ONTAP 클러스터와 통신하기 위해 다음과 같은 SAN 스토리지 드라이버를 제공합니다.  지원되는 액세스 모드는 다음과 같습니다: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| 운전사 | 규약 | 볼륨모드 | 지원되는 액세스 모드 | 지원되는 파일 시스템 


| `ontap-san`  a| 
FC를 통한 iSCSI SCSI
 a| 
차단하다
 a| 
RWO, ROX, RWX, RWOP
 a| 
파일 시스템 없음; 원시 블록 장치



| `ontap-san`  a| 
FC를 통한 iSCSI SCSI
 a| 
파일 시스템
 a| 
RWO, RWOP

ROX와 RWX는 파일 시스템 볼륨 모드에서 사용할 수 없습니다.
 a| 
`xfs`, `ext3` , `ext4`



| `ontap-san`  a| 
NVMe/TCP

참조하다<<NVMe/TCP에 대한 추가 고려 사항>> .
 a| 
차단하다
 a| 
RWO, ROX, RWX, RWOP
 a| 
파일 시스템 없음; 원시 블록 장치



| `ontap-san`  a| 
NVMe/TCP

참조하다<<NVMe/TCP에 대한 추가 고려 사항>> .
 a| 
파일 시스템
 a| 
RWO, RWOP

ROX와 RWX는 파일 시스템 볼륨 모드에서 사용할 수 없습니다.
 a| 
`xfs`, `ext3` , `ext4`



| `ontap-san-economy`  a| 
iSCSI
 a| 
차단하다
 a| 
RWO, ROX, RWX, RWOP
 a| 
파일 시스템 없음; 원시 블록 장치



| `ontap-san-economy`  a| 
iSCSI
 a| 
파일 시스템
 a| 
RWO, RWOP

ROX와 RWX는 파일 시스템 볼륨 모드에서 사용할 수 없습니다.
 a| 
`xfs`, `ext3` , `ext4`

|===
[WARNING]
====
* 사용 `ontap-san-economy` 지속적 볼륨 사용 횟수가 다음보다 높을 것으로 예상되는 경우에만link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["지원되는 ONTAP 볼륨 제한"^] .
* 사용 `ontap-nas-economy` 지속적 볼륨 사용 횟수가 다음보다 높을 것으로 예상되는 경우에만link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["지원되는 ONTAP 볼륨 제한"^] 그리고 `ontap-san-economy` 드라이버를 사용할 수 없습니다.
* 사용하지 마세요 `ontap-nas-economy` 데이터 보호, 재해 복구 또는 모빌리티가 필요할 것으로 예상되는 경우
* NetApp ontap-san을 제외한 모든 ONTAP 드라이버에서 Flexvol 자동 증가를 사용하지 않는 것을 권장합니다.  이 문제를 해결하기 위해 Trident 스냅샷 예약 사용을 지원하고 Flexvol 볼륨을 그에 따라 확장합니다.


====


== 사용자 권한

Trident 일반적으로 ONTAP 또는 SVM 관리자로 실행될 것으로 예상합니다. `admin` 클러스터 사용자 또는 `vsadmin` SVM 사용자 또는 동일한 역할을 가진 다른 이름을 가진 사용자입니다.  Amazon FSx for NetApp ONTAP 배포의 경우 Trident 클러스터를 사용하여 ONTAP 또는 SVM 관리자로 실행될 것으로 예상합니다. `fsxadmin` 사용자 또는 `vsadmin` SVM 사용자 또는 동일한 역할을 가진 다른 이름을 가진 사용자입니다.  그만큼 `fsxadmin` 사용자는 클러스터 관리자 사용자를 제한적으로 대체합니다.


NOTE: 당신이 사용하는 경우 `limitAggregateUsage` 매개변수, 클러스터 관리자 권한이 필요합니다.  Trident 와 함께 Amazon FSx for NetApp ONTAP 사용하는 경우 `limitAggregateUsage` 매개변수는 작동하지 않습니다 `vsadmin` 그리고 `fsxadmin` 사용자 계정.  이 매개변수를 지정하면 구성 작업이 실패합니다.

ONTAP 내에서 Trident 드라이버가 사용할 수 있는 보다 제한적인 역할을 만드는 것이 가능하지만 권장하지는 않습니다.  Trident 의 새로운 릴리스 대부분은 추가 API를 호출하므로 업그레이드가 어렵고 오류가 발생하기 쉽습니다.



== NVMe/TCP에 대한 추가 고려 사항

Trident 다음을 사용하여 NVMe(Non-Volatile Memory Express) 프로토콜을 지원합니다. `ontap-san` 운전자 포함:

* IPv6
* NVMe 볼륨의 스냅샷 및 복제본
* NVMe 볼륨 크기 조정
* Trident 외부에서 생성된 NVMe 볼륨을 가져와서 Trident 에서 수명 주기를 관리할 수 있도록 합니다.
* NVMe 네이티브 멀티패싱
* K8s 노드의 정상적 또는 비정상적 종료(24.06)


Trident 다음을 지원하지 않습니다.

* NVMe에서 기본적으로 지원되는 DH-HMAC-CHAP
* 장치 매퍼(DM) 다중 경로
* LUKS 암호화



NOTE: NVMe는 ONTAP REST API에서만 지원되며 ONTAPI(ZAPI)에서는 지원되지 않습니다.
