---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy-tridentctl.html 
keywords: deploy, Trident, methods, operator, tridentctl, helm, attributes, customize 
summary: Trident 설치 프로그램을 사용하여 배포를 사용자 정의할 수 있습니다. 
---
= tridentctl 설치 사용자 정의
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident 설치 프로그램을 사용하여 설치를 사용자 지정할 수 있습니다.



== 설치 프로그램에 대해 알아보세요

Trident 설치 프로그램을 사용하면 속성을 사용자 정의할 수 있습니다.  예를 들어, Trident 이미지를 개인 저장소에 복사한 경우 다음을 사용하여 이미지 이름을 지정할 수 있습니다. `--trident-image` .  Trident 이미지와 필요한 CSI 사이드카 이미지를 개인 저장소에 복사한 경우 다음을 사용하여 해당 저장소의 위치를 ​​지정하는 것이 더 좋을 수 있습니다. `--image-registry` 스위치는 다음 형식을 취합니다. `<registry FQDN>[:port]` .


IMPORTANT: 개인 저장소에 Trident 설치하는 경우 다음을 사용하는 경우 `--image-registry` 저장소 위치를 지정하려면 스위치를 사용하세요. `/netapp/` 저장소 경로에. 예를 들어: `./tridentctl install --image-registry <image-registry> -n <namespace>`

Kubernetes 배포판을 사용하는 경우 `kubelet` 일반적인 경로가 아닌 다른 경로에 데이터를 보관합니다. `/var/lib/kubelet` , 다음을 사용하여 대체 경로를 지정할 수 있습니다. `--kubelet-dir` .

설치 프로그램의 인수가 허용하는 것 이상으로 설치를 사용자 지정해야 하는 경우 배포 파일을 사용자 지정할 수도 있습니다.  를 사용하여 `--generate-custom-yaml` 매개변수는 설치 프로그램의 다음 YAML 파일을 생성합니다. `setup` 예배 규칙서:

* `trident-clusterrolebinding.yaml`
* `trident-deployment.yaml`
* `trident-crds.yaml`
* `trident-clusterrole.yaml`
* `trident-daemonset.yaml`
* `trident-service.yaml`
* `trident-namespace.yaml`
* `trident-serviceaccount.yaml`
* `trident-resourcequota.yaml`


이러한 파일을 생성한 후에는 필요에 따라 수정한 다음 사용할 수 있습니다. `--use-custom-yaml` 사용자 정의 배포를 설치합니다.

[source, console]
----
./tridentctl install -n trident --use-custom-yaml
----