= 
:allow-uri-read: 


. (_선택 사항_) 복원할 애플리케이션의 특정 리소스만 선택해야 하는 경우 특정 레이블로 표시된 리소스를 포함하거나 제외하는 필터링을 추가합니다.
+

NOTE: Trident Protect는 사용자가 선택한 리소스와의 관계로 인해 일부 리소스를 자동으로 선택합니다.  예를 들어, 영구 볼륨 클레임 리소스를 선택하고 연관된 Pod가 있는 경우 Trident Protect는 연관된 Pod도 복원합니다.

+
** *resourceFilter.resourceSelectionCriteria*: (필터링에 필요) 사용 `Include` 또는 `Exclude` resourceMatchers에 정의된 리소스를 포함하거나 제외합니다.  다음 resourceMatchers 매개변수를 추가하여 포함하거나 제외할 리소스를 정의합니다.
+
*** *resourceFilter.resourceMatchers*: resourceMatcher 객체의 배열입니다.  이 배열에 여러 요소를 정의하는 경우 OR 연산으로 일치하고, 각 요소 내부의 필드(그룹, 종류, 버전)는 AND 연산으로 일치합니다.
+
**** *resourceMatchers[].group*: (_선택 사항_) 필터링할 리소스 그룹입니다.
**** *resourceMatchers[].kind*: (_선택 사항_) 필터링할 리소스의 종류입니다.
**** *resourceMatchers[].version*: (_선택 사항_) 필터링할 리소스의 버전입니다.
**** *resourceMatchers[].names*: (_선택 사항_) 필터링할 리소스의 Kubernetes metadata.name 필드에 있는 이름입니다.
**** *resourceMatchers[].namespaces*: (_선택 사항_) 필터링할 리소스의 Kubernetes metadata.name 필드에 있는 네임스페이스입니다.
**** *resourceMatchers[].labelSelectors*: (_선택 사항_) 리소스의 Kubernetes metadata.name 필드에 있는 레이블 선택기 문자열입니다. https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors["쿠버네티스 문서"^] .  예를 들어: `"trident.netapp.io/os=linux"` .
+
예를 들어:

+
[source, yaml]
----
spec:
  resourceFilter:
    resourceSelectionCriteria: "Include"
    resourceMatchers:
      - group: my-resource-group-1
        kind: my-resource-kind-1
        version: my-resource-version-1
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
      - group: my-resource-group-2
        kind: my-resource-kind-2
        version: my-resource-version-2
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
----







