---
sidebar: sidebar 
permalink: trident-get-started/intro.html 
keywords: product overview, Trident, fsx, element, google cloud, cvs, architecture, node pod, controller pod, pods, csi, sidecar 
summary: 'Trident NetApp 에서 유지 관리하는 완벽한 지원 오픈 소스 프로젝트입니다.  이 기능은 CSI(Container Storage Interface)와 같은 업계 표준 인터페이스를 사용하여 컨테이너화된 애플리케이션의 지속성 요구 사항을 충족하는 데 도움이 되도록 설계되었습니다.' 
---
= Trident 에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident NetApp 에서 유지 관리하는 완벽하게 지원되는 오픈 소스 프로젝트입니다.  이 기능은 CSI(Container Storage Interface)와 같은 업계 표준 인터페이스를 사용하여 컨테이너화된 애플리케이션의 지속성 요구 사항을 충족하는 데 도움이 되도록 설계되었습니다.



== Trident 란 무엇인가요?

Netapp Trident FAS 하면 온프레미스 ONTAP 클러스터(AFF , NetApp , ASA), ONTAP Select, Cloud Volumes ONTAP, Element 소프트웨어(NetApp HCI, SolidFire), Azure NetApp Files, Amazon FSx for NetApp ONTAP, Google Cloud의 Cloud Volumes Service 등 퍼블릭 클라우드나 온프레미스에서 모든 인기 있는 NetApp 스토리지 플랫폼의 스토리지 리소스를 사용하고 관리할 수 있습니다.

Trident 는 기본적으로 통합되는 컨테이너 스토리지 인터페이스(CSI) 호환 동적 스토리지 오케스트레이터입니다.link:https://kubernetes.io/["쿠버네티스"^] .  Trident 클러스터의 각 워커 노드에 있는 노드 포드와 단일 컨트롤러 포드로 실행됩니다. 참조하다 link:../trident-get-started/architecture.html["Trident 아키텍처"] 자세한 내용은.

Trident 또한 NetApp 스토리지 플랫폼을 위한 Docker 생태계와의 직접적인 통합을 제공합니다.  NetApp Docker Volume Plugin(nDVP)은 스토리지 플랫폼에서 Docker 호스트로의 스토리지 리소스 프로비저닝 및 관리를 지원합니다. 참조하다 link:../trident-docker/deploy-docker.html["Docker에 Trident 배포"] 자세한 내용은.


NOTE: Kubernetes를 처음 사용하는 경우 다음 사항에 익숙해져야 합니다.link:https://kubernetes.io/docs/home/["쿠버네티스 개념 및 도구"^] .



== NetApp 제품과 Kubernetes 통합

NetApp 스토리지 제품 포트폴리오는 Kubernetes 클러스터의 여러 측면과 통합되어 고급 데이터 관리 기능을 제공하며, 이를 통해 Kubernetes 배포의 기능, 역량, 성능 및 가용성이 향상됩니다.

.Amazon FSx for NetApp ONTAP
[%collapsible]
====
link:https://www.netapp.com/aws/fsx-ontap/["Amazon FSx for NetApp ONTAP"^]NetApp ONTAP 스토리지 운영 체제를 기반으로 파일 시스템을 실행하고 실행할 수 있는 완전 관리형 AWS 서비스입니다.

====
.Azure NetApp Files
[%collapsible]
====
https://www.netapp.com/azure/azure-netapp-files/["Azure NetApp Files"^]NetApp 기반의 엔터프라이즈급 Azure 파일 공유 서비스입니다.  NetApp 에서 기대하는 성능과 풍부한 데이터 관리 기능을 통해 Azure에서 가장 까다로운 파일 기반 워크로드를 기본적으로 실행할 수 있습니다.

====
.Cloud Volumes ONTAP
[%collapsible]
====
link:https://www.netapp.com/cloud-services/cloud-volumes-ontap/["Cloud Volumes ONTAP"^]클라우드에서 ONTAP 데이터 관리 소프트웨어를 실행하는 소프트웨어 전용 스토리지 어플라이언스입니다.

====
.Google Cloud NetApp Volumes
[%collapsible]
====
link:https://bluexp.netapp.com/google-cloud-netapp-volumes?utm_source=GitHub&utm_campaign=Trident["Google Cloud NetApp Volumes"^]Google Cloud의 완전 관리형 파일 저장 서비스로, 고성능의 엔터프라이즈급 파일 저장을 제공합니다.

====
.엘리먼트 소프트웨어
[%collapsible]
====
https://www.netapp.com/data-management/element-software/["요소"^]스토리지 관리자가 성능을 보장하고 간소화되고 효율적인 스토리지 공간을 확보함으로써 작업 부하를 통합할 수 있도록 지원합니다.

====
.NetApp HCI
[%collapsible]
====
link:https://docs.netapp.com/us-en/hci/docs/concept_hci_product_overview.html["NetApp HCI"^]일상적인 작업을 자동화하고 인프라 관리자가 더 중요한 기능에 집중할 수 있도록 하여 데이터 센터의 관리와 규모를 간소화합니다.

Trident 기본 NetApp HCI 스토리지 플랫폼에 직접 컨테이너화된 애플리케이션의 스토리지 장치를 프로비저닝하고 관리할 수 있습니다.

====
.NetApp ONTAP
[%collapsible]
====
link:https://docs.netapp.com/us-en/ontap/index.html["NetApp ONTAP"^]NetApp 다중 프로토콜 통합 스토리지 운영 체제로, 모든 애플리케이션에 고급 데이터 관리 기능을 제공합니다.

ONTAP 시스템은 올플래시, 하이브리드 또는 올HDD 구성을 갖추고 있으며 온프레미스 FAS, AFA 및 ASA 클러스터, ONTAP Select, Cloud Volumes ONTAP 다양한 배포 모델을 제공합니다.  Trident 이러한 ONTAP 배포 모델을 지원합니다.

====