---
sidebar: sidebar 
permalink: trident-concepts/vol-access-groups.html 
keywords: volume access groups, element, solidfire, chap, Trident, hci, netapp hci, storage system, access volumes, 
summary: Trident 볼륨 액세스 그룹을 사용하는 방법에 대해 자세히 알아보세요. 
---
= 볼륨 액세스 그룹
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident 어떻게 사용하는지 자세히 알아보세요 https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html["볼륨 액세스 그룹"^] .


NOTE: CHAP를 사용하는 경우 이 섹션을 무시하세요. CHAP는 관리를 간소화하고 아래 설명된 확장 제한을 방지하는 데 권장됩니다.  또한, CSI 모드에서 Trident 사용하는 경우 이 섹션을 무시할 수 있습니다.  Trident 향상된 CSI 프로비저너로 설치될 경우 CHAP를 사용합니다.



== 볼륨 액세스 그룹에 대해 알아보세요

Trident 볼륨 액세스 그룹을 사용하여 프로비저닝하는 볼륨에 대한 액세스를 제어할 수 있습니다.  CHAP가 비활성화된 경우 CHAP는 다음과 같은 액세스 그룹을 찾을 것으로 예상합니다. `trident` 구성에서 하나 이상의 액세스 그룹 ID를 지정하지 않는 한.

Trident 구성된 액세스 그룹과 새 볼륨을 연결하지만 액세스 그룹 자체를 생성하거나 관리하지는 않습니다.  액세스 그룹은 스토리지 백엔드가 Trident 에 추가되기 전에 존재해야 하며, 해당 백엔드에서 프로비저닝된 볼륨을 잠재적으로 마운트할 수 있는 Kubernetes 클러스터의 모든 노드에서 iSCSI IQN을 포함해야 합니다.  대부분의 설치에는 클러스터의 모든 작업자 노드가 포함됩니다.

노드가 64개 이상인 Kubernetes 클러스터의 경우 여러 액세스 그룹을 사용해야 합니다.  각 액세스 그룹에는 최대 64개의 IQN이 포함될 수 있으며, 각 볼륨은 4개의 액세스 그룹에 속할 수 있습니다.  최대 4개의 액세스 그룹을 구성하면 최대 256개 노드로 구성된 클러스터의 모든 노드가 모든 볼륨에 액세스할 수 있습니다.  볼륨 액세스 그룹에 대한 최신 제한 사항은 다음을 참조하세요. https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html["여기"^] .

기본 구성을 사용하는 구성을 수정하는 경우 `trident` 다른 사용자도 사용하는 그룹에 액세스하려면 해당 ID를 포함합니다. `trident` 목록에 있는 그룹에 접근합니다.
