---
sidebar: sidebar 
permalink: trident-reco/backup.html 
keywords: data protection, replication, dr, disaster recovery, snapmirror, back up, snapshot, element, volume replication 
summary: Trident 및 Trident 사용하여 생성된 볼륨에 대한 보호 및 복구 옵션에 대해 알아보세요.  지속성 요구 사항이 있는 각 애플리케이션에 대해 데이터 보호 및 복구 전략이 있어야 합니다. 
---
= 데이터 보호 및 재해 복구
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident 및 Trident 사용하여 생성된 볼륨에 대한 보호 및 복구 옵션에 대해 알아보세요.  지속성 요구 사항이 있는 각 애플리케이션에 대해 데이터 보호 및 복구 전략이 있어야 합니다.



== Trident 복제 및 복구

재해 발생 시 Trident 복구하기 위한 백업을 만들 수 있습니다.



=== Trident 복제

Trident Kubernetes CRD를 사용하여 자체 상태를 저장하고 관리하고 Kubernetes 클러스터 etcd를 사용하여 메타데이터를 저장합니다.

.단계
. Kubernetes 클러스터 etcd를 사용하여 백업합니다.link:https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#backing-up-an-etcd-cluster["Kubernetes: etcd 클러스터 백업"^] .
. FlexVol volume 에 백업 아티팩트 배치
+

NOTE: NetApp FlexVol 있는 SVM을 다른 SVM과의 SnapMirror 관계로 보호하는 것이 좋습니다.





=== Trident 회수

Kubernetes CRD와 Kubernetes 클러스터 etcd 스냅샷을 사용하면 Trident 복구할 수 있습니다.

.단계
. 대상 SVM에서 Kubernetes etcd 데이터 파일과 인증서가 포함된 볼륨을 마스터 노드로 설정될 호스트에 마운트합니다.
. Kubernetes 클러스터에 관련된 모든 필수 인증서를 아래에 복사하세요. `/etc/kubernetes/pki` 그리고 etcd 멤버 파일은 다음과 같습니다. `/var/lib/etcd` .
. etcd 백업을 사용하여 Kubernetes 클러스터를 복원합니다.link:https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster["Kubernetes: etcd 클러스터 복원"^] .
. 달리다 `kubectl get crd` 모든 Trident 사용자 정의 리소스가 나타났는지 확인하고 Trident 객체를 검색하여 모든 데이터를 사용할 수 있는지 확인합니다.




== SVM 복제 및 복구

Trident 복제 관계를 구성할 수 없지만 스토리지 관리자는 다음을 사용할 수 있습니다. https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-concept.html["ONTAP SnapMirror"^] SVM을 복제합니다.

재해가 발생하면 SnapMirror 대상 SVM을 활성화하여 데이터 제공을 시작할 수 있습니다.  시스템이 복구되면 기본으로 다시 전환할 수 있습니다.

.이 작업에 관하여
SnapMirror SVM 복제 기능을 사용할 때 다음 사항을 고려하세요.

* SVM-DR이 활성화된 각 SVM에 대해 별도의 백엔드를 만들어야 합니다.
* SVM-DR을 지원하는 백엔드에 복제가 필요 없는 볼륨이 프로비저닝되는 것을 방지하기 위해 필요할 때만 복제된 백엔드를 선택하도록 스토리지 클래스를 구성합니다.
* 애플리케이션 관리자는 복제와 관련된 추가 비용과 복잡성을 이해하고 이 프로세스를 시작하기 전에 복구 계획을 신중하게 고려해야 합니다.




=== SVM 복제

사용할 수 있습니다link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-workflow-concept.html["ONTAP: SnapMirror SVM 복제"^] SVM 복제 관계를 생성합니다.

SnapMirror 사용하면 복제할 내용을 제어하는 ​​옵션을 설정할 수 있습니다.  수행할 때 선택한 옵션을 알아야 합니다.<<Trident 사용한 SVM 복구>> .

* link:https://docs.netapp.com/us-en/ontap/data-protection/replicate-entire-svm-config-task.html["-동일성-참 유지"^]SVM 구성 전체를 복제합니다.
* link:https://docs.netapp.com/us-en/ontap/data-protection/exclude-lifs-svm-replication-task.html["-discard-configs 네트워크"^]LIF 및 관련 네트워크 설정은 제외됩니다.
* link:https://docs.netapp.com/us-en/ontap/data-protection/exclude-network-name-service-svm-replication-task.html["-신원-보존 거짓"^]볼륨과 보안 구성만 복제합니다.




=== Trident 사용한 SVM 복구

Trident SVM 오류를 자동으로 감지하지 않습니다.  재해가 발생하면 관리자는 수동으로 Trident 장애 조치를 새 SVM으로 시작할 수 있습니다.

.단계
. 예약된 SnapMirror 전송과 진행 중인 SnapMirror 전송을 취소하고, 복제 관계를 끊고, 소스 SVM을 중지한 다음 SnapMirror 대상 SVM을 활성화합니다.
. 당신이 지정한 경우 `-identity-preserve false` 또는 `-discard-config network` SVM 복제를 구성할 때 다음을 업데이트하세요. `managementLIF` 그리고 `dataLIF` Trident 백엔드 정의 파일에서.
. 확인하다 `storagePrefix` Trident 백엔드 정의 파일에 있습니다.  이 매개변수는 변경할 수 없습니다.  생략 `storagePrefix` 백엔드 업데이트가 실패하게 됩니다.
. 다음을 사용하여 새로운 대상 SVM 이름을 반영하도록 모든 필수 백엔드를 업데이트합니다.
+
[listing]
----
./tridentctl update backend <backend-name> -f <backend-json-file> -n <namespace>
----
. 당신이 지정한 경우 `-identity-preserve false` 또는 `discard-config network` 모든 애플리케이션 포드를 반송해야 합니다.
+

NOTE: 당신이 지정한 경우 `-identity-preserve true` Trident 에서 프로비저닝한 모든 볼륨은 대상 SVM이 활성화되면 데이터 제공을 시작합니다.





== 볼륨 복제 및 복구

Trident SnapMirror 복제 관계를 구성할 수 없지만 스토리지 관리자는 다음을 사용할 수 있습니다.link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["ONTAP SnapMirror 복제 및 복구"^] Trident 에서 생성된 볼륨을 복제합니다.

그런 다음 복구된 볼륨을 Trident 로 가져올 수 있습니다.link:../trident-use/vol-import.html["tridentctl 볼륨 가져오기"] .


NOTE: 가져오기가 지원되지 않습니다. `ontap-nas-economy` , `ontap-san-economy` , 또는 `ontap-flexgroup-economy` 운전자.



== 스냅샷 데이터 보호

다음을 사용하여 데이터를 보호하고 복원할 수 있습니다.

* 영구 볼륨(PV)의 Kubernetes 볼륨 스냅샷을 생성하기 위한 외부 스냅샷 컨트롤러와 CRD입니다.
+
link:../trident-use/vol-snapshots.html["볼륨 스냅샷"]

* ONTAP 스냅샷을 사용하면 볼륨의 전체 내용을 복원하거나 개별 파일이나 LUN을 복구할 수 있습니다.
+
link:https://docs.netapp.com/us-en/ontap/data-protection/manage-local-snapshot-copies-concept.html["ONTAP 스냅샷"^]


