---
sidebar: sidebar 
permalink: trident-reco/security-reco.html 
keywords: security, chap, trident, namespace, nve, nae, encryption, volume encryption, aggregate encryption 
summary: 여기에 나열된 권장 사항을 사용하여 Trident 설치가 안전한지 확인하세요. 
---
= 보안
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
여기에 나열된 권장 사항을 사용하여 Trident 설치가 안전한지 확인하세요.



== Trident 자체 네임스페이스에서 실행

안정적인 저장소를 보장하고 잠재적인 악성 활동을 차단하려면 애플리케이션, 애플리케이션 관리자, 사용자 및 관리 애플리케이션이 Trident 객체 정의나 포드에 액세스하지 못하도록 하는 것이 중요합니다.

다른 애플리케이션과 사용자를 Trident 에서 분리하려면 항상 Trident 자체 Kubernetes 네임스페이스에 설치하십시오.(`trident` ).  Trident 자체 네임스페이스에 배치하면 Kubernetes 관리 담당자만 Trident 포드와 네임스페이스 CRD 객체에 저장된 아티팩트(해당되는 경우 백엔드 및 CHAP 비밀 등)에 액세스할 수 있습니다.  관리자만 Trident 네임스페이스에 액세스할 수 있도록 허용해야 하며 이를 통해 액세스할 수 있습니다. `tridentctl` 애플리케이션.



== ONTAP SAN 백엔드에서 CHAP 인증 사용

Trident ONTAP SAN 워크로드에 대한 CHAP 기반 인증을 지원합니다(사용 `ontap-san` 그리고 `ontap-san-economy` 운전자).  NetApp 호스트와 스토리지 백엔드 간 인증을 위해 Trident 와 함께 양방향 CHAP를 사용할 것을 권장합니다.

SAN 스토리지 드라이버를 사용하는 ONTAP 백엔드의 경우 Trident 양방향 CHAP를 설정하고 CHAP 사용자 이름과 비밀번호를 관리할 수 있습니다. `tridentctl` .  참조하다link:../trident-use/ontap-san-prep.html["ONTAP SAN 드라이버로 백엔드 구성을 준비합니다."^] Trident ONTAP 백엔드에서 CHAP를 구성하는 방법을 이해합니다.



== NetApp HCI 및 SolidFire 백엔드에서 CHAP 인증 사용

NetApp 호스트와 NetApp HCI 및 SolidFire 백엔드 간의 인증을 보장하기 위해 양방향 CHAP를 배포할 것을 권장합니다.  Trident 테넌트당 두 개의 CHAP 암호가 포함된 비밀 객체를 사용합니다.  Trident 가 설치되면 CHAP 비밀을 관리하고 저장합니다. `tridentvolume` 해당 PV에 대한 CR 객체입니다.  PV를 생성하면 Trident CHAP 비밀을 사용하여 iSCSI 세션을 시작하고 CHAP를 통해 NetApp HCI 및 SolidFire 시스템과 통신합니다.


NOTE: Trident 에서 생성된 볼륨은 어떤 볼륨 액세스 그룹과도 연관되지 않습니다.



== NVE 및 NAE와 함께 Trident 사용

NetApp ONTAP 디스크가 도난당하거나 반환되거나 다른 용도로 사용되는 경우 중요한 데이터를 보호하기 위해 저장 데이터 암호화를 제공합니다. 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["NetApp 볼륨 암호화 구성 개요"^] .

* 백엔드에서 NAE가 활성화된 경우 Trident 에서 프로비저닝된 모든 볼륨은 NAE가 활성화됩니다.
+
** NVE 암호화 플래그를 설정할 수 있습니다. `""` NAE 지원 볼륨을 생성합니다.


* 백엔드에서 NAE가 활성화되지 않은 경우 NVE 암호화 플래그가 설정되지 않는 한 Trident 에서 프로비저닝된 모든 볼륨은 NVE가 활성화됩니다. `false` (기본값) 백엔드 구성에서.


[NOTE]
====
NAE 지원 백엔드의 Trident 에서 생성된 볼륨은 NVE 또는 NAE로 암호화되어야 합니다.

* NVE 암호화 플래그를 설정할 수 있습니다. `true` Trident 백엔드 구성에서 NAE 암호화를 재정의하고 볼륨별로 특정 암호화 키를 사용합니다.
* NVE 암호화 플래그를 다음으로 설정 `false` NAE 지원 백엔드에서는 NAE 지원 볼륨을 생성합니다.  NVE 암호화 플래그를 설정하여 NAE 암호화를 비활성화할 수 없습니다. `false` .


====
* NVE 암호화 플래그를 명시적으로 설정하여 Trident 에서 NVE 볼륨을 수동으로 생성할 수 있습니다. `true` .


백엔드 구성 옵션에 대한 자세한 내용은 다음을 참조하세요.

* link:../trident-use/ontap-san-examples.html["ONTAP SAN 구성 옵션"]
* link:../trident-use/ontap-nas-examples.html["ONTAP NAS 구성 옵션"]

