---
sidebar: sidebar 
permalink: trident-protect/trident-protect-generate-support-bundle.html 
keywords: trident, protect, bundle, support, netapp, custom, resource, file 
summary: 'Trident Protect를 사용하면 관리자는 관리 중인 클러스터와 앱에 대한 로그, 메트릭, 토폴로지 정보 등 NetApp 지원에 유용한 정보가 포함된 번들을 생성할 수 있습니다. 인터넷에 연결되어 있는 경우 사용자 정의 리소스(CR) 파일을 사용하여 NetApp 지원 사이트(NSS)에 지원 번들을 업로드할 수 있습니다.' 
---
= Trident Protect 지원 번들 생성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident Protect를 사용하면 관리자는 관리 중인 클러스터와 앱에 대한 로그, 메트릭, 토폴로지 정보 등 NetApp 지원에 유용한 정보가 포함된 번들을 생성할 수 있습니다. 인터넷에 연결되어 있는 경우 사용자 정의 리소스(CR) 파일을 사용하여 NetApp 지원 사이트(NSS)에 지원 번들을 업로드할 수 있습니다.

[role="tabbed-block"]
====
.CR을 사용하여 지원 번들을 만듭니다.
--
.단계
. 사용자 정의 리소스(CR) 파일을 만들고 이름을 지정합니다(예: `trident-protect-support-bundle.yaml` ).
. 다음 속성을 구성합니다.
+
** *metadata.name*: (_필수_) 이 사용자 지정 리소스의 이름입니다. 사용자 환경에 맞게 고유하고 적절한 이름을 선택하세요.
** *spec.triggerType*: (_필수_) 지원 번들이 즉시 생성되는지, 아니면 예약되는지를 결정합니다.  예약된 번들 생성은 UTC 기준 오전 12시에 이루어집니다.  가능한 값:
+
*** 예정됨
*** 수동


** *spec.uploadEnabled*: (_선택 사항_) 지원 번들이 생성된 후 NetApp 지원 사이트에 업로드할지 여부를 제어합니다.  지정하지 않으면 기본값으로 설정됩니다. `false` .  가능한 값:
+
*** true
*** false (기본값)


** *spec.dataWindowStart*: (_선택 사항_) 지원 번들에 포함된 데이터 창이 시작되어야 하는 날짜와 시간을 지정하는 RFC 3339 형식의 날짜 문자열입니다.  지정하지 않으면 기본적으로 24시간 전으로 설정됩니다.  지정할 수 있는 가장 빠른 날짜는 7일 전입니다.
+
YAML 예시:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: AutoSupportBundle
metadata:
  name: trident-protect-support-bundle
spec:
  triggerType: Manual
  uploadEnabled: true
  dataWindowStart: 2024-05-05T12:30:00Z
----


. 다음을 채운 후 `trident-protect-support-bundle.yaml` 올바른 값으로 파일을 만들고 CR을 적용합니다.
+
[source, console]
----
kubectl apply -f trident-protect-support-bundle.yaml -n trident-protect
----


--
.CLI를 사용하여 지원 번들을 만듭니다.
--
.단계
. 괄호 안의 값을 사용자 환경의 정보로 바꿔서 지원 번들을 만듭니다.  그만큼 `trigger-type` 번들이 즉시 생성되는지 또는 생성 시간이 일정에 따라 결정되는지 여부를 결정하고 다음을 수행할 수 있습니다. `Manual` 또는 `Scheduled` .  기본 설정은 다음과 같습니다. `Manual` .
+
예를 들어:

+
[source, console]
----
tridentctl-protect create autosupportbundle <my-bundle-name> --trigger-type <trigger-type> -n trident-protect
----


--
====


== 지원 번들을 모니터링하고 검색합니다.

두 가지 방법 중 하나를 사용하여 지원 번들을 만든 후에는 생성 진행 상황을 모니터링하고 로컬 시스템으로 검색할 수 있습니다.

.단계
. 기다리다 `status.generationState` 도달하다 `Completed` 상태. 다음 명령을 사용하여 생성 진행 상황을 모니터링할 수 있습니다.
+
[source, console]
----
kubectl get autosupportbundle trident-protect-support-bundle -n trident-protect
----
. 지원 번들을 로컬 시스템으로 가져옵니다. 완성된 AutoSupport 번들에서 복사 명령을 가져옵니다.
+
[source, console]
----
kubectl describe autosupportbundle trident-protect-support-bundle -n trident-protect
----
+
찾아라 `kubectl cp` 출력에서 명령을 선택하고 대상 인수를 원하는 로컬 디렉토리로 바꿔서 실행합니다.


