---
sidebar: sidebar 
permalink: trident-protect/trident-protect-cli.html 
keywords: trident, protect, command line utility, cli, netapp, custom, resources 
summary: protectctl 명령을 사용하면 Trident Protect 사용자 정의 리소스를 만들고 상호 작용할 수 있습니다. 
---
= Trident Protect CLI 플러그인을 설치하세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident Protect 명령줄 플러그인을 사용할 수 있습니다. 이 플러그인은 Trident 의 확장 기능입니다. `tridentctl` Trident Protect 사용자 정의 리소스(CR)를 생성하고 상호 작용할 수 있는 유틸리티입니다.



== Trident Protect CLI 플러그인을 설치하세요

명령줄 유틸리티를 사용하려면 먼저 클러스터에 액세스하는 데 사용하는 컴퓨터에 유틸리티를 설치해야 합니다.  컴퓨터에서 x64 또는 ARM CPU를 사용하는지 여부에 따라 다음 단계를 따르세요.

[role="tabbed-block"]
====
.Linux AMD64 CPU용 플러그인 다운로드
--
.단계
. Trident Protect CLI 플러그인을 다운로드하세요:
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.06.0/tridentctl-protect-linux-amd64
----


--
.Linux ARM64 CPU용 플러그인 다운로드
--
.단계
. Trident Protect CLI 플러그인을 다운로드하세요:
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.06.0/tridentctl-protect-linux-arm64
----


--
.Mac AMD64 CPU용 플러그인 다운로드
--
.단계
. Trident Protect CLI 플러그인을 다운로드하세요:
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.06.0/tridentctl-protect-macos-amd64
----


--
.Mac ARM64 CPU용 플러그인 다운로드
--
.단계
. Trident Protect CLI 플러그인을 다운로드하세요:
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.06.0/tridentctl-protect-macos-arm64
----


--
====
. 플러그인 바이너리에 대한 실행 권한을 활성화합니다.
+
[source, console]
----
chmod +x tridentctl-protect
----
. 플러그인 바이너리를 PATH 변수에 정의된 위치에 복사합니다.  예를 들어, `/usr/bin` 또는 `/usr/local/bin` (높은 권한이 필요할 수 있음):
+
[source, console]
----
cp ./tridentctl-protect /usr/local/bin/
----
. 선택적으로 플러그인 바이너리를 홈 디렉토리의 원하는 위치에 복사할 수 있습니다.  이 경우 해당 위치가 PATH 변수의 일부인지 확인하는 것이 좋습니다.
+
[source, console]
----
cp ./tridentctl-protect ~/bin/
----



NOTE: 플러그인을 PATH 변수의 위치에 복사하면 다음을 입력하여 플러그인을 사용할 수 있습니다. `tridentctl-protect` 또는 `tridentctl protect` 어느 위치에서나.



== Trident CLI 플러그인 도움말 보기

플러그인의 기능에 대한 자세한 도움말을 얻으려면 내장된 플러그인 도움말 기능을 사용할 수 있습니다.

.단계
. 도움말 기능을 사용하여 사용 지침을 확인하세요.
+
[source, console]
----
tridentctl-protect help
----




== 명령 자동 완성 활성화

Trident Protect CLI 플러그인을 설치한 후 특정 명령에 대한 자동 완성을 활성화할 수 있습니다.

[role="tabbed-block"]
====
.Bash 셸에 대한 자동 완성을 활성화합니다.
--
.단계
. 완성 스크립트를 다운로드하세요:
+
[source, console]
----
curl -L -O https://github.com/NetApp/tridentctl-protect/releases/download/25.06.0/tridentctl-completion.bash
----
. 스크립트를 포함할 새 디렉토리를 홈 디렉토리에 만듭니다.
+
[source, console]
----
mkdir -p ~/.bash/completions
----
. 다운로드한 스크립트를 다음으로 이동합니다. `~/.bash/completions` 예배 규칙서:
+
[source, console]
----
mv tridentctl-completion.bash ~/.bash/completions/
----
. 다음 줄을 추가하세요 `~/.bashrc` 홈 디렉토리에 있는 파일:
+
[source, console]
----
source ~/.bash/completions/tridentctl-completion.bash
----


--
.Z 셸에 대한 자동 완성을 활성화합니다.
--
.단계
. 완성 스크립트를 다운로드하세요:
+
[source, console]
----
curl -L -O https://github.com/NetApp/tridentctl-protect/releases/download/25.06.0/tridentctl-completion.zsh
----
. 스크립트를 포함할 새 디렉토리를 홈 디렉토리에 만듭니다.
+
[source, console]
----
mkdir -p ~/.zsh/completions
----
. 다운로드한 스크립트를 다음으로 이동합니다. `~/.zsh/completions` 예배 규칙서:
+
[source, console]
----
mv tridentctl-completion.zsh ~/.zsh/completions/
----
. 다음 줄을 추가하세요 `~/.zprofile` 홈 디렉토리에 있는 파일:
+
[source, console]
----
source ~/.zsh/completions/tridentctl-completion.zsh
----


--
====
.결과
다음 셸 로그인 시 tridentctl-protect 플러그인을 사용하여 명령 자동 완성 기능을 사용할 수 있습니다.
