---
sidebar: sidebar 
permalink: trident-reference/trident-cl.html 
keywords: command-line, options, logging, kubernetes, docker, ports 
summary: Trident Trident 오케스트레이터에 대한 여러 가지 명령줄 옵션을 제공하고 특정 포트를 통해 통신합니다. 
---
= 명령줄 옵션
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident Trident 오케스트레이터에 대한 여러 가지 명령줄 옵션을 제공합니다.  이러한 옵션을 사용하여 배포를 수정할 수 있습니다.



== 벌채 반출

`-debug`:: 디버깅 출력을 활성화합니다.
`-loglevel <level>`:: 로깅 수준(디버그, 정보, 경고, 오류, 치명적)을 설정합니다.  기본적으로 info로 설정됩니다.




== 쿠버네티스

`-k8s_pod`:: 이 옵션을 사용하거나 `-k8s_api_server` Kubernetes 지원을 활성화합니다.  이것을 설정하면 Trident 포함된 Pod의 Kubernetes 서비스 계정 자격 증명을 사용하여 API 서버에 접속합니다.  이 기능은 Trident 서비스 계정이 활성화된 Kubernetes 클러스터에서 Pod로 실행되는 경우에만 작동합니다.
`-k8s_api_server <insecure-address:insecure-port>`:: 이 옵션을 사용하거나 `-k8s_pod` Kubernetes 지원을 활성화합니다.  이 옵션을 지정하면 Trident 제공된 안전하지 않은 주소와 포트를 사용하여 Kubernetes API 서버에 연결합니다.  이를 통해 Trident 포드 외부에 배포할 수 있습니다. 하지만 API 서버에 대한 안전하지 않은 연결만 지원합니다.  안전하게 연결하려면 포드에 Trident 배치하세요. `-k8s_pod` 옵션.




== 도커

`-volume_driver <name>`:: Docker 플러그인을 등록할 때 사용되는 드라이버 이름입니다.  기본값으로 설정됨 `netapp` .
`-driver_port <port-number>`:: UNIX 도메인 소켓이 아닌 이 포트에서 수신합니다.
`-config <file>`:: 필수. 백엔드 구성 파일에 대한 경로를 지정해야 합니다.




== 나머지

`-address <ip-or-host>`:: Trident의 REST 서버가 수신해야 하는 주소를 지정합니다.  기본값은 localhost입니다.  로컬호스트에서 수신하고 Kubernetes Pod 내부에서 실행하는 경우 REST 인터페이스는 Pod 외부에서 직접 액세스할 수 없습니다.  사용 `-address ""` Pod IP 주소에서 REST 인터페이스에 접근할 수 있도록 합니다.
+
--

CAUTION: Trident REST 인터페이스는 127.0.0.1(IPv4의 경우) 또는 [::1](IPv6의 경우)에서만 수신하고 서비스하도록 구성할 수 있습니다.

--
`-port <port-number>`:: Trident의 REST 서버가 수신해야 하는 포트를 지정합니다.  기본값은 8000입니다.
`-rest`:: REST 인터페이스를 활성화합니다.  기본값은 true입니다.

